import Link from 'next/link';
import type { Metadata } from 'next';
import { Fraunces, Inter } from 'next/font/google';
import { BRAND } from '@/lib/brand';
import { TN_CITIES, TN_MOST_ACTIVE, TN_TOTALS, TN_INCOME_NOTE } from './data';
import './report.css';

/* ===========================================================================
   THE TENNESSEE PERKUL REPORT  ·  /reports/tennessee
   ---------------------------------------------------------------------------
   An unlisted long-scroll data feature. Deliberately NOT in the site nav and
   NOT in sitemap.ts — the only way in is a direct link.

   The centrepiece is the FULL ranking: every sampled city, its average score
   and its player count. No minimum-sample cut-off, no filtering — the whole
   board is on the page. Income appears once, at the end, as a curiosity.

   All data comes from ./data.ts, generated by scripts/build-tn-report-data.js.
   Charts are hand-built CSS/SVG. No charting library, no client JavaScript.
   =========================================================================== */

const editorialSerif = Fraunces({
  subsets: ['latin'],
  variable: '--tnr-font-serif',
  display: 'swap',
});

const editorialSans = Inter({
  subsets: ['latin'],
  variable: '--tnr-font-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: `The Tennessee ${BRAND.name} Report — All 148 Cities Ranked`,
  description: `Every one of Tennessee's ${TN_TOTALS.cities} sampled cities, ranked by average ${BRAND.name} score, from ${TN_TOTALS.topScore.toLocaleString()} down to ${TN_TOTALS.lowScore.toLocaleString()} — based on ${TN_TOTALS.users.toLocaleString()} players and ${TN_TOTALS.tests.toLocaleString()} tests, benchmarked against 2.5 million registered players.`,
  keywords: [
    'Tennessee word game',
    'Tennessee city rankings',
    'Tennessee Perkul report',
    'smartest cities in Tennessee',
    'Nashville vs Memphis',
    'word game data study',
  ],
  openGraph: {
    title: `The Tennessee ${BRAND.name} Report`,
    description: `All ${TN_TOTALS.cities} Tennessee cities ranked by average score. ${TN_TOTALS.users.toLocaleString()} players. ${TN_TOTALS.tests.toLocaleString()} tests.`,
    type: 'article',
    url: `https://${BRAND.domain}/reports/tennessee`,
    siteName: BRAND.name,
  },
  twitter: { card: 'summary_large_image' },
  alternates: { canonical: `https://${BRAND.domain}/reports/tennessee` },
};

/* ---------------------------------------------------------------------------
   DERIVED VIEWS
--------------------------------------------------------------------------- */

const fmt = (v: number) => v.toLocaleString('en-US');

/**
 * The national benchmark's player base, written for prose: "2.5 million".
 * The benchmark is not a small control group — it is the entire registered
 * player base, which is the point worth making wherever it appears.
 */
const NATIONAL_PLAYERS = `${(TN_TOTALS.nationalUsers / 1_000_000)
  .toFixed(1)
  .replace(/\.0$/, '')} million`;

/** The three cities at the top of the board. */
const PODIUM = TN_CITIES.slice(0, 3);

/** The three at the bottom, worst first, for the mirror-image podium. */
const DULLEST = TN_CITIES.slice(-3).reverse();

/** How Tennessee compares to Perkul's all-players average. */
const NATIONAL_DELTA = TN_TOTALS.meanCityScore - TN_TOTALS.nationalAvg;

/** Number of distinct city-vs-city matchups, for the income footnote. */
const PAIR_COUNT = (TN_TOTALS.cities * (TN_TOTALS.cities - 1)) / 2;

/** Savannah's position on the board, quoted in the income example. */
const EXAMPLE_RANK = TN_CITIES.findIndex((c) => c.city === TN_INCOME_NOTE.exampleCity.city) + 1;

/** How many cities clear the national benchmark. */
const ABOVE_NATIONAL = TN_CITIES.filter((c) => c.score > TN_TOTALS.nationalAvg).length;

/** Ranks 4–25 get the full treatment: name, players, score and a scaled bar. */
const FEATURED = TN_CITIES.slice(3, 25);

/** Everything from rank 26 down, shown as a dense but complete grid. */
const REMAINDER = TN_CITIES.slice(25);

const HERO_STATS = [
  { num: fmt(TN_TOTALS.cities), label: 'Cities ranked' },
  { num: fmt(TN_TOTALS.users), label: 'Players' },
  { num: fmt(TN_TOTALS.tests), label: 'Tests taken' },
  { num: fmt(TN_TOTALS.meanCityScore), label: 'Average city score' },
];

/**
 * Bar scale. Every score in the sample sits between 7,700 and 9,100, so the
 * bars are scaled across a slightly wider window to keep the differences
 * legible. This means the bars do NOT start at zero — called out on the page.
 */
const BAR_FLOOR = 7600;
const BAR_CEIL = 9150;
const barPct = (score: number) =>
  Math.max(3, Math.min(100, ((score - BAR_FLOOR) / (BAR_CEIL - BAR_FLOOR)) * 100));

/** Four colour bands so the board reads at a glance. */
function band(score: number): 'elite' | 'strong' | 'mid' | 'low' {
  if (score >= 8900) return 'elite';
  if (score >= 8400) return 'strong';
  if (score >= 8000) return 'mid';
  return 'low';
}

const BANDS = [
  { key: 'elite', label: '8,900+' },
  { key: 'strong', label: '8,400 – 8,899' },
  { key: 'mid', label: '8,000 – 8,399' },
  { key: 'low', label: 'Under 8,000' },
];

/* -- most-active chart --------------------------------------------------- */
const maxUsers = Math.max(...TN_MOST_ACTIVE.map((c) => c.users));

/* ---------------------------------------------------------------------------
   STRUCTURED DATA
--------------------------------------------------------------------------- */
const reportJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Dataset',
  name: `The Tennessee ${BRAND.name} Report`,
  description: `Average ${BRAND.name} score and player count for ${TN_TOTALS.cities} Tennessee cities, based on ${TN_TOTALS.users} players and ${TN_TOTALS.tests} completed tests.`,
  url: `https://${BRAND.domain}/reports/tennessee`,
  inLanguage: 'en-US',
  isAccessibleForFree: true,
  creator: { '@type': 'Organization', name: BRAND.name, url: `https://${BRAND.domain}` },
  spatialCoverage: { '@type': 'Place', name: 'Tennessee' },
  variableMeasured: ['Average score by city', 'Unique players by city', 'Tests completed by city'],
};

/* =========================================================================
   PAGE
   ========================================================================= */
export default function TennesseeReportPage() {
  return (
    <div className={`tnr ${editorialSerif.variable} ${editorialSans.variable}`}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(reportJsonLd) }}
      />

      {/* ================================================================
          1 — HERO
          ================================================================ */}
      <header className="tnr-hero">
        <div className="tnr-wrap">
          <span className="tnr-hero__badge">
            <b>P</b> A {BRAND.name} Data Feature
          </span>

          <h1 className="tnr-hero__title">
            All {TN_TOTALS.cities} Tennessee Cities, <em>Ranked</em>
          </h1>

          <p className="tnr-hero__sub">
            We took every Tennessee city in our sample — no minimum, no filtering — and ranked them
            by average {BRAND.name} score.
          </p>

          <div className="tnr-hero__intro">
            <p>
              We picked one state and went deep. Tennessee gave us enough players spread across
              enough towns to ask a simple question: how does each city actually do, how do they
              stack up against each other, and how do they compare to the rest of the country?
            </p>
            <p>
              So we ran it as a small case study — {fmt(TN_TOTALS.cities)} cities, side by side,
              measured against the national {BRAND.name} average of {NATIONAL_PLAYERS} registered
              players. What came back was a board that looks nothing like the one we expected.
            </p>
          </div>

          <div className="tnr-strip">
            {HERO_STATS.map((s) => (
              <div className="tnr-strip__item" key={s.label}>
                <span className="tnr-strip__num">{s.num}</span>
                <span className="tnr-strip__label">{s.label}</span>
              </div>
            ))}
          </div>

          <p className="tnr-note tnr-hero__note">
            Scores range from {fmt(TN_TOTALS.lowScore)} to {fmt(TN_TOTALS.topScore)}. City sizes
            vary a lot, so player counts are shown beside every single city — read the small samples
            with that in mind. Every city is also held up against {NATIONAL_PLAYERS} registered{' '}
            {BRAND.name} players nationwide.
          </p>
        </div>
      </header>

      {/* ================================================================
          2 — TENNESSEE vs THE NATION
          ================================================================ */}
      <section className="tnr-section">
        <div className="tnr-wrap tnr-wrap--tight">
          <div className="tnr-head tnr-head--center tnr-reveal">
            <span className="tnr-kicker">First, the benchmark</span>
            <h2 className="tnr-h2">How Tennessee Stacks Up</h2>
            <p className="tnr-lede">
              Before comparing cities to each other, it helps to know where the whole state sits.
              Averaged across all {TN_TOTALS.cities} cities, Tennessee lands{' '}
              <strong>{fmt(NATIONAL_DELTA)} points above</strong> the national {BRAND.name} average
              — and that national number is not a small control group. It is the average of{' '}
              <strong>{NATIONAL_PLAYERS} registered players</strong>.
            </p>
          </div>

          <div className="tnr-curio tnr-reveal">
            <div className="tnr-curio__side">
              <span className="tnr-curio__label">Tennessee average</span>
              <span className="tnr-curio__num">{fmt(TN_TOTALS.meanCityScore)}</span>
              <span className="tnr-curio__sub">
                {fmt(TN_TOTALS.cities)} cities · {fmt(TN_TOTALS.users)} players
              </span>
            </div>
            <span className="tnr-curio__vs">
              <b>+{fmt(NATIONAL_DELTA)}</b>
              <i>Tennessee edge</i>
            </span>
            <div className="tnr-curio__side" data-tone="neutral">
              <span className="tnr-curio__label">National average</span>
              <span className="tnr-curio__num">{fmt(TN_TOTALS.nationalAvg)}</span>
              <span className="tnr-curio__sub">
                All {NATIONAL_PLAYERS} registered {BRAND.name} players
              </span>
            </div>
          </div>

          <p className="tnr-note" style={{ marginTop: '1.5rem' }}>
            Every city on the board below is also measured against this {fmt(TN_TOTALS.nationalAvg)}
            {' '}line — {ABOVE_NATIONAL} of the {TN_TOTALS.cities} cities beat it.
          </p>
        </div>
      </section>

      {/* ================================================================
          3 — THE PODIUMS  (sharpest and dullest, as a mirrored pair)
          ================================================================ */}
      <section className="tnr-section tnr-section--band" id="podiums">
        <div className="tnr-wrap">
          <div className="tnr-head tnr-head--center tnr-reveal">
            <span className="tnr-kicker">The top of the board</span>
            <h2 className="tnr-h2">Tennessee’s Three Sharpest Cities</h2>
          </div>

          <div className="tnr-podium tnr-reveal">
            {PODIUM.map((c, i) => (
              <article className="tnr-pod" data-place={i + 1} key={c.city}>
                <span className="tnr-pod__medal">{i + 1}</span>
                <h3 className="tnr-pod__city">{c.city}</h3>
                <span className="tnr-pod__score">{fmt(c.score)}</span>
                <span className="tnr-pod__label">Average score</span>
                <span className="tnr-pod__players">
                  {fmt(c.users)} players · {fmt(c.tests)} tests
                </span>
              </article>
            ))}
          </div>

          {/* -- and the other end of the same board -------------------- */}
          <div
            className="tnr-head tnr-head--center tnr-reveal"
            style={{ marginTop: '4.5rem' }}
          >
            <span className="tnr-kicker">The bottom of the board</span>
            <h2 className="tnr-h2">And the Three Dullest</h2>
            <p className="tnr-lede">
              Worth noting before you scroll: all three are among the wealthiest places in the
              state.
            </p>
          </div>

          <div className="tnr-podium tnr-reveal" data-tone="low">
            {DULLEST.map((c, i) => (
              <article className="tnr-pod" data-place={i + 1} data-tone="low" key={c.city}>
                <span className="tnr-pod__medal">{TN_TOTALS.cities - i}</span>
                <h3 className="tnr-pod__city">{c.city}</h3>
                <span className="tnr-pod__score">{fmt(c.score)}</span>
                <span className="tnr-pod__label">Average score</span>
                <span className="tnr-pod__players">
                  {fmt(c.users)} players · ${fmt(c.income)} median income
                </span>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ================================================================
          4 — THE FULL BOARD  (centrepiece)
          ================================================================ */}
      <section className="tnr-section" id="board">
        <div className="tnr-wrap">
          <div className="tnr-head tnr-reveal">
            <span className="tnr-kicker">The full board</span>
            <h2 className="tnr-h2">Every City, Every Score</h2>
            <p className="tnr-lede">
              Ranks 4 through 25 in detail, then all {TN_TOTALS.cities} cities in full. Bar length
              tracks the average score; the pill shows how many players that city’s number is built
              on.
            </p>
          </div>

          <div className="tnr-legend tnr-legend--bands tnr-reveal">
            {BANDS.map((b) => (
              <span key={b.key}>
                <i data-band={b.key} /> {b.label}
              </span>
            ))}
          </div>

          {/* -- ranks 4–25, full rows ---------------------------------- */}
          <ol className="tnr-board tnr-reveal">
            {FEATURED.map((c, i) => (
              <li className="tnr-row" key={c.city}>
                <span className="tnr-row__rank">{i + 4}</span>
                <span className="tnr-row__city">{c.city}</span>
                <span className="tnr-row__players">{fmt(c.users)}</span>
                <span className="tnr-row__track">
                  <span
                    className="tnr-row__fill"
                    data-band={band(c.score)}
                    style={{ width: `${barPct(c.score)}%`, animationDelay: `${i * 45}ms` }}
                  />
                </span>
                <span className="tnr-row__score">{fmt(c.score)}</span>
              </li>
            ))}
          </ol>

          {/* -- ranks 26+, dense complete grid ------------------------- */}
          <h3 className="tnr-h3 tnr-subhead">
            Ranks 26–{TN_TOTALS.cities}
            <span className="tnr-subhead__note">every remaining city in the sample</span>
          </h3>

          <ol className="tnr-grid-board tnr-reveal">
            {REMAINDER.map((c, i) => (
              <li className="tnr-cell" data-band={band(c.score)} key={c.city}>
                <span className="tnr-cell__rank">{i + 26}</span>
                <span className="tnr-cell__city">{c.city}</span>
                <span className="tnr-cell__players">{fmt(c.users)}p</span>
                <span className="tnr-cell__score">{fmt(c.score)}</span>
              </li>
            ))}
          </ol>

          <p className="tnr-axisnote">
            Bars are scaled from {fmt(BAR_FLOOR)} to {fmt(BAR_CEIL)} so the differences are visible.
            The scale does not start at zero. “p” = players sampled.
          </p>
        </div>
      </section>

      {/* ================================================================
          5 — WHERE THE PLAYERS ARE
          ================================================================ */}
      <section className="tnr-section tnr-section--ink">
        <div className="tnr-wrap">
          <div className="tnr-head tnr-reveal">
            <span className="tnr-kicker">Turnout</span>
            <h2 className="tnr-h2">Where Tennessee Actually Played</h2>
            <p className="tnr-lede">
              Score is one story, turnout is another. These cities brought the biggest player bases
              — and therefore the steadiest averages on the board.
            </p>
          </div>

          <div className="tnr-bars tnr-reveal">
            {TN_MOST_ACTIVE.map((c, i) => (
              <div className="tnr-bar" key={c.city}>
                <span className="tnr-bar__city">{c.city}</span>
                <span className="tnr-bar__track">
                  <span
                    className="tnr-bar__fill"
                    style={{
                      width: `${(c.users / maxUsers) * 100}%`,
                      animationDelay: `${i * 90}ms`,
                    }}
                  />
                  <span className="tnr-bar__inside">{fmt(c.users)} players</span>
                </span>
                <span className="tnr-bar__val">{fmt(c.score)}</span>
              </div>
            ))}
          </div>

          <p className="tnr-axisnote">
            Bar length = unique players. The number on the right is that city’s average score.
          </p>
        </div>
      </section>

      {/* ================================================================
          6 — THE INCOME PATTERN
          ================================================================ */}
      <section className="tnr-section" id="income">
        <div className="tnr-wrap tnr-wrap--tight">
          <div className="tnr-head tnr-reveal">
            <span className="tnr-kicker">The interesting tidbit</span>
            <h2 className="tnr-h2">The Richer the City, the Lower the Score</h2>
            <p className="tnr-lede">
              Here is the strangest thing in the data. Line the {TN_TOTALS.cities} cities up by
              median household income and the scores run almost exactly backwards: as income goes
              up, the {BRAND.name} average goes down. Not loosely — this trend continues almost as a
              rule.
            </p>
          </div>

          {/* -- the worked example the pattern is easiest to see in ----- */}
          <div className="tnr-example tnr-reveal">
            <article className="tnr-example__card" data-tone="rich">
              <span className="tnr-example__tag">Wealthiest city in the sample</span>
              <h3 className="tnr-example__city">{TN_INCOME_NOTE.richestCity.city}</h3>
              <div className="tnr-example__pair">
                <span>
                  <b>${fmt(TN_INCOME_NOTE.richestCity.income)}</b>
                  <i>median income</i>
                </span>
                <span>
                  <b data-role="score">{fmt(TN_INCOME_NOTE.richestCity.score)}</b>
                  <i>average score — dead last of {TN_TOTALS.cities}</i>
                </span>
              </div>
            </article>

            <article className="tnr-example__card" data-tone="poor">
              <span className="tnr-example__tag">Near the bottom for income</span>
              <h3 className="tnr-example__city">{TN_INCOME_NOTE.exampleCity.city}</h3>
              <div className="tnr-example__pair">
                <span>
                  <b>${fmt(TN_INCOME_NOTE.exampleCity.income)}</b>
                  <i>median income</i>
                </span>
                <span>
                  <b data-role="score">{fmt(TN_INCOME_NOTE.exampleCity.score)}</b>
                  <i>
                    average score — {EXAMPLE_RANK === 3 ? 'third best' : `no. ${EXAMPLE_RANK}`} of{' '}
                    {TN_TOTALS.cities}
                  </i>
                </span>
              </div>
            </article>
          </div>

          <p className="tnr-example__note">
            {TN_INCOME_NOTE.richestCity.city} earns roughly{' '}
            {Math.round(TN_INCOME_NOTE.richestCity.income / TN_INCOME_NOTE.exampleCity.income)}×
            what {TN_INCOME_NOTE.exampleCity.city} does, and scored{' '}
            {fmt(TN_INCOME_NOTE.exampleCity.score - TN_INCOME_NOTE.richestCity.score)} points lower.
            Across all {fmt(PAIR_COUNT)} possible city-vs-city matchups, the poorer city scored
            higher{' '}
            <strong>{TN_INCOME_NOTE.holdsPct}%</strong> of the time (correlation r ={' '}
            {TN_INCOME_NOTE.correlation}).
          </p>

          <h3 className="tnr-h3 tnr-subhead">
            And it holds in bulk
            <span className="tnr-subhead__note">not just at the extremes</span>
          </h3>

          <div className="tnr-curio tnr-reveal">
            <div className="tnr-curio__side">
              <span className="tnr-curio__label">
                Poorest {TN_INCOME_NOTE.quartileSize} cities
              </span>
              <span className="tnr-curio__num">{fmt(TN_INCOME_NOTE.lowIncomeAvg)}</span>
              <span className="tnr-curio__sub">average score</span>
            </div>
            <span className="tnr-curio__vs">
              <b>{fmt(TN_INCOME_NOTE.gap)}</b>
              <i>point gap</i>
            </span>
            <div className="tnr-curio__side" data-tone="low">
              <span className="tnr-curio__label">
                Richest {TN_INCOME_NOTE.quartileSize} cities
              </span>
              <span className="tnr-curio__num">{fmt(TN_INCOME_NOTE.highIncomeAvg)}</span>
              <span className="tnr-curio__sub">average score</span>
            </div>
          </div>

          <p className="tnr-note" style={{ marginTop: '1.5rem' }}>
            We have no explanation for this, and we are not claiming one. It is not evidence that
            money makes you worse with words — {BRAND.name} and income measure completely different
            things, and this is a sample of people who chose to play a word game, not a survey of
            residents. Wealthier areas may simply attract more casual, distracted, play-once
            players. It is, however, a remarkably clean pattern.
          </p>
        </div>
      </section>

      {/* ================================================================
          7 — LIMITS
          ================================================================ */}
      <section className="tnr-section tnr-section--band">
        <div className="tnr-wrap tnr-wrap--tight">
          <div className="tnr-head tnr-head--center tnr-reveal">
            <span className="tnr-kicker">Read it fairly</span>
            <h2 className="tnr-h2">What This Board Is (and Isn’t)</h2>
          </div>

          <div className="tnr-not tnr-reveal">
            <ul>
              <li data-tone="yes">
                It is a complete ranking of how each city’s sampled players performed on {BRAND.name}
              </li>
              <li>It is not an IQ ranking, or a ranking of “best” and “worst” places</li>
              <li>
                It is not a census — small cities rest on few players, so their averages swing more
              </li>
              <li>It is not a claim that non-players in those cities would score the same</li>
            </ul>
          </div>

          <div className="tnr-method">
            <h3>Method</h3>
            <p>
              Each city’s figure is the average score of its sampled players across{' '}
              {TN_TOTALS.testsPerPlayer} tests per player on average. The national benchmark of{' '}
              {fmt(TN_TOTALS.nationalAvg)} is the all-time average across {BRAND.name}’s{' '}
              {NATIONAL_PLAYERS} registered players. Locations are estimated from the network
              location of each session, so they indicate roughly where a test originated — not a
              player’s permanent residence.
            </p>
          </div>
        </div>
      </section>

      {/* ================================================================
          8 — CTA
          ================================================================ */}
      <section className="tnr-cta">
        <div className="tnr-wrap tnr-cta__inner">
          <div className="tnr-head tnr-head--center" style={{ marginBottom: 0 }}>
            <span className="tnr-kicker">Your move</span>
            <h2 className="tnr-cta__title">
              Where Does <em>Your City</em> Land?
            </h2>
          </div>

          <div className="tnr-cta__body">
            <p>
              Every game played shifts these averages. If your city is further down the board than
              you would like, there is an obvious fix.
            </p>
          </div>

          <Link className="tnr-btn" href="/">
            Play {BRAND.name} →
          </Link>

          <p className="tnr-cta__kicker">
            Play {BRAND.name}. Post your score. Move your city up the board.
          </p>
        </div>
      </section>
    </div>
  );
}
