/**
 * PERKUL — daily games #016–#020 (2026-08-12 → 2026-08-16)
 */
import { buildGame } from './format';

export const GAME_016 = buildGame({
  date: '2026-08-12',
  gameNumber: 16,
  rounds: [
    [1, 'mixed',
      ['BASKET|n|a container made of woven material', 'SNAPPY|adj|brisk and lively; smart', 'MELT|v|to become liquid through heat',
       '^CULM|n|the hollow stem of a grass or cereal|Botanical vocabulary for a grass stalk. Four letters, and easily read as a typo for CALM.',
       '*BASKRANT'],
      'BASKRANT looks like a basketry or packaging term, and traditional trades legitimately contain words like it.',
      'CULM is the trap: a precise botanical noun that reads as a mistyping of CALM or CURL.'],
    [2, 'mixed',
      ['CANDLE|n|a wax cylinder with a wick', 'SPLINTER|n|a small sharp fragment', 'ROWDY|adj|noisy and disorderly',
       '^SLAG|n|waste matter from smelting|Also a verb, to criticise harshly. Four letters and unattractive, so it looks invented.',
       '*CANDRIC'],
      'CANDRIC uses the -IC ending of chemical adjectives on a familiar stem, which is how a fake earns instant authority.',
      'SLAG is the decoy: real in metallurgy and in British slang, but blunt enough to look fabricated.'],
    [2, 'mixed',
      ['GARDEN|n|a piece of ground for growing plants', 'PLUMP|adj|pleasantly full and rounded', 'STOOP|v|to bend forward and down',
       '^SWALE|n|a low tract of moist land|Landscape and drainage vocabulary. Looks like a blend of SWALE’s neighbours SWALLOW and SCALE.',
       '*GARDRANT'],
      'GARDRANT looks like horticultural jargon, and the shape suggests something you might read on a plant label.',
      'SWALE is the trap: a real and increasingly common landscaping term that looks like a coinage.'],
    [3, 'mixed',
      ['MORTAR|n|a mixture used to bind bricks; a bowl for grinding', 'FLAIL|v|to wave or thrash about wildly', 'CRISPY|adj|pleasantly brittle',
       '^SCUTTLE|n|a container for coal; a hatch on a ship|Both senses are real, as is the verb. The word does too many jobs to be believed.',
       '*MORTRANT'],
      'MORTRANT sits close to the real MORDANT and shares a stem with MORTAR, which makes it look thoroughly documented.',
      'SCUTTLE is the decoy: three legitimate senses in one word, which makes players assume one was invented.'],
    [3, 'mixed',
      ['TROUGHS|n|long open containers for food or water', 'BLEARY|adj|dim and unfocused, as tired eyes', 'HITCH|v|to fasten; to travel by lift',
       '^WITHE|n|a flexible twig used for binding|Basket-making vocabulary. Looks like a fragment of WITHER or WITH.',
       '*BLEARANT'],
      'BLEARANT looks like an ophthalmic term, and medical vocabulary is where players most readily accept unfamiliar words.',
      'WITHE is the trap: a real craft noun that looks like an incomplete word.'],
    [3, 'mixed',
      ['CANVAS|n|a strong coarse cloth', 'DRENCH|v|to wet thoroughly', 'PERT|adj|attractively lively; impudent',
       '^SCARP|n|a steep slope or cliff|Geographical, and the root of ESCARPMENT. Looks like a typo for SCARF or SHARP.',
       '*CANVRANT'],
      'CANVRANT looks like a term from sailmaking or painting, both of which supply genuinely obscure real vocabulary.',
      'SCARP is the decoy: a legitimate landform noun that sits one letter from two much commoner words.'],
    [3, 'visual-family',
      ['SIZZLING|adj|extremely hot; making a hissing sound', 'FIZZLE|v|to end feebly after a promising start', 'GRIZZLE|v|to whimper or complain quietly',
       '^SWIZZLE|n|a mixed drink; a stick for stirring it|A swizzle stick is real, and so is the drink. Looks like the invented member.',
       '*SPIZZLE'],
      'SPIZZLE is protected by a family of real -IZZLE words, where the shared pattern is the entire disguise.',
      'SWIZZLE is the decoy: genuine bar vocabulary that reads as nonsense beside its rhymes.'],
    [4, 'mixed',
      ['INDOLENT|adj|habitually lazy', 'SCRIVENER|n|a clerk or copyist', 'BALK|v|to hesitate or refuse to proceed',
       '^PALFREY|n|a docile horse for ordinary riding|Historical but genuinely recorded. Looks like invented mock-medieval vocabulary.',
       '*INDOLANT'],
      'INDOLANT is one vowel from INDOLENT, so players who know the real adjective may believe they have simply misremembered it.',
      'PALFREY is the trap: a real word for a riding horse that reads like something invented for a fantasy novel.'],
    [4, 'mixed',
      ['CONTRITE|adj|feeling remorse', 'SWATH|n|a strip cut by a mower; a broad area', 'MORDANT|adj|sharply critical; a dye fixative',
       '^ORISON|n|a prayer|Literary and old, but recorded and used. Looks like a blend of ORIGIN and HORIZON.',
       '*CONTRANT'],
      'CONTRANT looks like a legal term and shares its opening with several real words, so it slides past unexamined.',
      'ORISON is the decoy: a genuine noun for a prayer that reads as a mistake for HORIZON.'],
    [5, 'mixed',
      ['INTREPID|adj|fearless and adventurous', 'SOLECISM|n|a grammatical mistake or breach of etiquette', 'DESULTORY|adj|lacking a plan or purpose',
       '^EMPYREAN|adj|of the highest heaven; sublime|A real word for the celestial. Looks like invented cosmology.',
       '*INTREPANT'],
      'INTREPANT keeps INTREPID’s stem and takes -ANT, so it reads like an adjective from an older, grander register.',
      'EMPYREAN is the trap: entirely legitimate in literary English, but the spelling looks manufactured.'],
  ],
});

export const GAME_017 = buildGame({
  date: '2026-08-13',
  gameNumber: 17,
  rounds: [
    [1, 'mixed',
      ['MIRROR|n|a reflecting surface of glass', 'CHATTER|v|to talk rapidly about trivial things', 'BOLD|adj|confident and courageous',
       '^HASP|n|a hinged fastening for a door or lid|The metal loop a padlock passes through. Four letters, so it reads as a coinage.',
       '*MIRRANT'],
      'MIRRANT looks like an optical term, and optics genuinely supplies words that sound like this.',
      'HASP is the trap: standard hardware vocabulary that looks like a fabricated syllable.'],
    [2, 'mixed',
      ['BLANKET|n|a large piece of woollen material for warmth', 'SQUEAK|v|to make a short high sound', 'HEARTY|adj|warm and enthusiastic; substantial',
       '^SCRIM|n|a light open-weave fabric|Used in theatre and building. Looks like a truncation of SCRIMMAGE.',
       '*BLANKRANT'],
      'BLANKRANT looks like a textile or printing term, and both trades produce unfamiliar genuine vocabulary.',
      'SCRIM is the decoy: real in theatre, film and plastering, but it reads as an abbreviation.'],
    [2, 'mixed',
      ['CARPET|n|a thick woven floor covering', 'GRUMBLING|adj|complaining in a low voice', 'TOUGH|adj|strong; difficult',
       '^NAP|n|the raised surface of a fabric; a short sleep|Both senses are real. Three letters, so it looks like filler.',
       '*CARPRANT'],
      'CARPRANT looks like a flooring-trade term, and the invented word borrows a stem from the same round.',
      'NAP is the trap: two ordinary senses in three letters, which makes players assume it cannot be the serious answer.'],
    [3, 'mixed',
      ['THIMBLE|n|a cap worn to protect the finger when sewing', 'WHIRL|v|to spin rapidly', 'SLACK|adj|not taut; careless',
       '^BODKIN|n|a blunt thick needle for drawing tape through cloth|Sewing vocabulary, and famous from Hamlet. Looks invented.',
       '*THIMBRANT'],
      'THIMBRANT looks like a haberdashery term, and losing the E makes the invention feel older.',
      'BODKIN is the decoy: a real needle, and a real Shakespearean word, that reads like a nonsense noun.'],
    [3, 'mixed',
      ['CROCKERY|n|plates, dishes and cups collectively', 'RUEFUL|adj|expressing regret with humour', 'FLAP|v|to move up and down noisily',
       '^EWER|n|a large jug with a wide mouth|A pitcher for water, usually antique. Four letters and vowel-heavy.',
       '*CROCKANT'],
      'CROCKANT looks like a ceramics term, and the -ANT ending on a familiar stem is the game’s most reliable disguise.',
      'EWER is the trap: a genuine noun for a jug that looks like a random arrangement of letters.'],
    [3, 'visual-family',
      ['HURDLE|n|a barrier to jump; an obstacle', 'CURDLE|v|to separate into curds; to sour', 'GIRDLE|n|a belt or encircling band',
       '^HURTLE|v|to move at great speed, often uncontrollably|Real and common, but in this row of near-rhymes it looks like the invention.',
       '*MURDLE'],
      'MURDLE is hidden by four genuine -URDLE and -URTLE words, and the pattern removes any impulse to check.',
      'HURTLE is the decoy: entirely standard, but so close in shape to HURDLE that players assume one was invented.'],
    [3, 'mixed',
      ['SALVER|n|a tray, usually of metal, for serving', 'PEAKY|adj|looking pale and unwell', 'DRAFT|n|a preliminary version; a current of air',
       '^TREEN|adj|made of wood|A collector’s term for small wooden domestic objects. Looks like an invented plural of TREE.',
       '*SALVANT'],
      'SALVANT looks like a chemical or medical term, and it shares its stem with a real noun in the same round.',
      'TREEN is the trap: a genuine antiques term that looks like an invented plural.'],
    [4, 'mixed',
      ['PERFUNCTORY|adj|done without real interest or care', 'GLEBE|n|land belonging to a parish church', 'SNIDE|adj|derogatory in a sly way',
       '^BURGEON|v|to grow or increase rapidly|"Burgeoning demand." Looks like a blend of BURDEN and SURGEON.',
       '*PERFUNCTANT'],
      'PERFUNCTANT keeps a real Latin root and takes -ANT, so it looks like the adjective a bureaucrat would use.',
      'BURGEON is the decoy: common in business journalism, but its shape suggests two unrelated words stuck together.'],
    [4, 'mixed',
      ['ACRID|adj|unpleasantly bitter or pungent', 'TITHE|n|a tenth of income paid as a levy', 'GAMUT|n|the complete range of something',
       '^SPILLIKIN|n|a thin stick used in a game of pick-up-sticks|The game of spillikins is genuinely recorded. Looks invented.',
       '*ACRIDANT'],
      'ACRIDANT looks like a chemical descriptor, and it borrows the authority of a real adjective in the same round.',
      'SPILLIKIN is the trap: a real if antique game piece whose name reads as pure invention.'],
    [5, 'mixed',
      ['INEXORABLE|adj|impossible to stop or prevent', 'CATHOLICITY|n|universality; broad-mindedness', 'CHARNEL|adj|associated with death and corpses',
       '^INANITION|n|exhaustion from lack of nourishment|A real medical and literary noun. Looks like a blend of INANE and INITIATION.',
       '*INEXORANT'],
      'INEXORANT keeps the real root of INEXORABLE and takes -ANT, so it reads as the concise form of a familiar adjective.',
      'INANITION is the decoy: a genuine noun for wasting away that looks assembled from unrelated parts.'],
  ],
});

export const GAME_018 = buildGame({
  date: '2026-08-14',
  gameNumber: 18,
  rounds: [
    [1, 'mixed',
      ['BRIDGE|n|a structure spanning an obstacle', 'FLUFFY|adj|light and soft', 'TOSS|v|to throw lightly',
       '^QUAY|n|a platform where ships load and unload|Pronounced "key", which is precisely why it looks invented.',
       '*BRIDGRANT'],
      'BRIDGRANT looks like a civil-engineering term, and engineering vocabulary is full of genuinely odd words.',
      'QUAY is the trap: an entirely ordinary harbour noun whose spelling gives no clue to its sound.'],
    [2, 'mixed',
      ['HAMMER|n|a tool for driving nails', 'BREEZY|adj|pleasantly windy; cheerfully casual', 'GRIP|v|to hold firmly',
       '^ADZE|n|a tool like an axe with an arched blade|A carpenter’s tool. The DZ pairing looks impossible in English.',
       '*HAMMRANT'],
      'HAMMRANT looks like a term from metalworking, and the missing vowel makes it read as older vocabulary.',
      'ADZE is the decoy: a real and still-used tool whose spelling looks fabricated.'],
    [2, 'mixed',
      ['CURTAIN|n|a hanging cloth screening a window', 'WOBBLY|adj|unsteady', 'CHOMP|v|to chew noisily',
       '^SASH|n|a window frame that slides; a band worn over the shoulder|Both senses are real and unrelated, which feels like a trick.',
       '*CURTRANT'],
      'CURTRANT looks like an interior-fittings term, and it takes its stem from a plain noun in the same round.',
      'SASH is the trap: two legitimate senses that seem too different to belong to one small word.'],
    [3, 'visual-family',
      ['LATCH|n|a bar fastening a door', 'THATCHED|adj|roofed with straw or reeds', 'SNATCH|v|to grab quickly',
       '^HATCHMENT|n|a diamond-shaped panel bearing a coat of arms|Heraldic vocabulary, hung after a death. Looks invented.',
       '*FLATCH'],
      'FLATCH hides among real -ATCH words, and the FL- opening is entirely ordinary in English.',
      'HATCHMENT is the decoy: a genuine heraldic term that looks like HATCH with a suffix bolted on.'],
    [3, 'mixed',
      ['FURNITURE|n|the movable articles in a room', 'SPRINGY|adj|returning quickly to shape', 'JOLT|n|an abrupt rough movement',
       '^ESCUTCHEON|n|a shield bearing a coat of arms|Also a protective plate around a keyhole. Long, French-looking, easy to reject.',
       '*FURNITRANT'],
      'FURNITRANT looks like a trade term from cabinetmaking, and length lends invented words credibility.',
      'ESCUTCHEON is the trap: real in heraldry and hardware, but its spelling looks like an elaborate joke.'],
    [3, 'mixed',
      ['CELLAR|n|an underground storage room', 'MURKINESS|n|the state of being dark or obscure', 'CLING|v|to hold on tightly',
       '^FIRKIN|n|a small cask, historically a quarter barrel|Brewing vocabulary, still used by real ale brewers. Looks invented.',
       '*CELLRANT'],
      'CELLRANT looks like a brewing or storage term, and it shares its stem with a real noun in the same round.',
      'FIRKIN is the decoy: a genuine cask size that reads as pure nonsense to anyone outside brewing.'],
    [3, 'mixed',
      ['PLASTER|n|a paste that hardens for coating walls', 'SCANTY|adj|barely sufficient in amount', 'HEFT|n|weight; to lift something heavy',
       '^SPANDREL|n|the space between an arch and its framing|Architectural vocabulary. Looks like a blend of SPANIEL and SPINDLE.',
       '*PLASTRANT'],
      'PLASTRANT looks like a building-materials term, and it borrows a stem from a real noun beside it.',
      'SPANDREL is the trap: precise architectural vocabulary that reads as an invented compound.'],
    [4, 'mixed',
      ['VOLUBLE|adj|talking fluently and at length', 'CRAVEN|adj|contemptibly cowardly', 'SPATULA|n|a flat implement for spreading or lifting',
       '^SUBALTERN|n|a junior officer; a subordinate|British military and academic usage. Looks like invented bureaucracy.',
       '*VOLUBRANT'],
      'VOLUBRANT keeps a real Latin root and takes -ANT, so it looks like an adjective for a fluent speaker.',
      'SUBALTERN is the decoy: real in military and postcolonial writing, but it reads as a fabricated rank.'],
    [4, 'mixed',
      ['VESTRY|n|a room in a church for clergy and records', 'GAUDY|adj|extravagantly bright or showy', 'SKULK|v|to move stealthily; to lurk',
       '^HOBBLE|v|to walk with difficulty; to tie an animal’s legs together|Both senses are real. Short and comic-sounding, so it looks invented.',
       '*SKULKANT'],
      'SKULKANT applies -ANT to a real verb, exactly as English produced CLAIMANT and SUPPLICANT.',
      'HOBBLE is the decoy: a genuine verb in two senses whose sound makes players treat it as a joke entry.'],
    [5, 'mixed',
      ['PROPINQUITY|n|nearness in place or relationship', 'FUNGIBLE|adj|mutually interchangeable', 'MINATORY|adj|expressing a threat',
       '^APPOSITE|adj|strikingly appropriate|Not APPOSITE’s lookalike OPPOSITE — it means apt. That collision makes it look invented.',
       '*PROPINQUANT'],
      'PROPINQUANT keeps a genuine Latin root and takes -ANT, so it looks like the adjective belonging to PROPINQUITY.',
      'APPOSITE is the trap: a real and useful adjective that players read as a misprint of OPPOSITE.'],
  ],
});

export const GAME_019 = buildGame({
  date: '2026-08-15',
  gameNumber: 19,
  rounds: [
    [1, 'mixed',
      ['BOTTLES|n|containers with narrow necks', 'STICKY|adj|tending to adhere', 'CARRY|v|to support and move something',
       '^BUTT|n|a large cask; the thicker end of a tool|Several plain senses, all real. It looks like a joke entry.',
       '*BOTTRANT'],
      'BOTTRANT looks like a bottling or brewing term, and industrial vocabulary really does look like this.',
      'BUTT is the trap: multiple ordinary senses in a word players expect to be a punchline.'],
    [2, 'mixed',
      ['PILLOW|n|a cushion supporting the head', 'GRUBBY|adj|dirty', 'SHRUG|v|to raise the shoulders slightly',
       '^BOLSTER|n|a long firm pillow; to support|Both the pillow and the verb are real. Looks like a blend of BOLT and HOLSTER.',
       '*PILLRANT'],
      'PILLRANT looks like a pharmaceutical term, and drug-adjacent vocabulary is where -ANT thrives.',
      'BOLSTER is the decoy: real in furniture and in argument, yet it looks assembled from two other words.'],
    [2, 'mixed',
      ['SILVER|n|a precious greyish-white metal', 'PATCHY|adj|uneven in quality or coverage', 'DRIFT|v|to be carried slowly by wind or water',
       '^ASSAY|n|a test of metal purity; an attempt|Used in metallurgy and in older prose. Looks like a misspelling of ESSAY.',
       '*SILVRANT'],
      'SILVRANT looks like a metallurgical term, and dropping the E makes an invented word look properly derived.',
      'ASSAY is the trap: real in mining and chemistry, but nearly identical to a far commoner word.'],
    [3, 'mixed',
      ['COMPASS|n|an instrument showing direction', 'GRITTY|adj|containing grit; courageously unglamorous', 'HAUL|v|to pull with effort',
       '^BINNACLE|n|the housing for a ship’s compass|Nautical vocabulary. Looks like a blend of BARNACLE and PINNACLE.',
       '*COMPASSANT'],
      'COMPASSANT looks like a navigational term, and its stem is a real instrument in the same round.',
      'BINNACLE is the decoy: a genuine piece of ship’s equipment whose name looks like a deliberate mash-up.'],
    [3, 'mixed',
      ['ANCHOR|n|a heavy device that moors a ship', 'SLIMY|adj|covered with an unpleasant slippery film', 'VEER|v|to change direction suddenly',
       '^HAWSER|n|a thick rope or cable for mooring|Nautical vocabulary. Looks like a blend of HAWK and TROUSER.',
       '*ANCHRANT'],
      'ANCHRANT looks like a marine-engineering term, and the invention borrows a stem from the round itself.',
      'HAWSER is the trap: a real and specific mooring rope that reads as a fabrication.'],
    [3, 'mixed',
      ['RIGGING|n|the ropes and chains supporting a ship’s masts', 'CHOPPY|adj|of water: rough with small waves', 'STOW|v|to pack away carefully',
       '^GUNWALE|n|the upper edge of a boat’s side|Pronounced "gunnel", which is why the spelling looks invented.',
       '*RIGGRANT'],
      'RIGGRANT looks like a term from sailmaking, and it shares its opening with a real noun in the same round.',
      'GUNWALE is the decoy: entirely standard among sailors, but its spelling and pronunciation disagree completely.'],
    [3, 'mixed',
      ['LIGHTHOUSE|n|a tower with a beacon warning ships', 'SPRAY|n|liquid blown in fine droplets', 'BRINY|adj|salty; of the sea',
       '^SEXTANT|n|an instrument for measuring angles in navigation|A real and famous instrument. The X makes it look invented.',
       '*LIGHTRANT'],
      'LIGHTRANT looks like an optical or maritime-safety term, and the compound shape makes it feel official.',
      'SEXTANT is the trap: unarguably real, which punishes players who assume the strangest-looking word must be false.'],
    [4, 'mixed',
      ['LEEWARD|adj|on the sheltered side, away from the wind', 'FLOTILLA|n|a small fleet of ships', 'ABAFT|adv|toward the stern of a ship',
       '^SCUPPERS|n|openings in a ship’s side that drain water|Plural nautical vocabulary. Looks like an invented cousin of SUPPER.',
       '*LEEWRANT'],
      'LEEWRANT looks like a sailing term, and the round’s nautical register makes the invention feel at home.',
      'SCUPPERS is the decoy: real drainage openings on a deck, but the word looks like a joke about dinner.'],
    [4, 'visual-family',
      ['SHACKLES|n|metal fastenings for the wrists or ankles', 'CRACKLE|n|a series of short sharp sounds', 'TACKLE|n|equipment; a set of ropes and pulleys',
       '^SPECKLED|adj|marked with small spots|Real and plain, but in a row of -CKLE words it looks like the odd one out.',
       '*FRACKLE'],
      'FRACKLE hides among real -CKLE words, and the FR- cluster is entirely ordinary in English.',
      'SPECKLED is the decoy: unarguably real, which makes it a cruel trap in a patterned round.'],
    [5, 'mixed',
      ['ANTEDILUVIAN|adj|extremely old-fashioned', 'CAPACIOUS|adj|having a lot of space inside', 'JETTISON|v|to throw or drop from a ship or aircraft',
       '^ORLOP|n|the lowest deck of a ship|Genuine nautical architecture. Looks like a palindrome someone invented for fun.',
       '*ANTEDILUANT'],
      'ANTEDILUANT keeps a real Latin root and takes -ANT, so it looks like a technical adjective from geology.',
      'ORLOP is the trap: a real deck on a wooden ship whose name looks like nonsense.'],
  ],
});

export const GAME_020 = buildGame({
  date: '2026-08-16',
  gameNumber: 20,
  label: 'Bank closer',
  rounds: [
    [1, 'mixed',
      ['LIBRARY|n|a collection of books, or the building housing it', 'SPOTTY|adj|marked with spots; uneven', 'LEAN|v|to incline from the vertical',
       '^TOME|n|a large, heavy or scholarly book|"A weighty tome." Four letters, so it reads as a clipped invention.',
       '*LIBRANT'],
      'LIBRANT looks like a bibliographic term, and the stem is unmistakably real, which does most of the work.',
      'TOME is the trap: entirely ordinary in book reviews, but short enough to look fabricated.'],
    [2, 'mixed',
      ['PENCIL|n|an instrument for writing with graphite', 'SCRAWL|v|to write hurriedly and untidily', 'CRISPNESS|n|the quality of being firm or clear',
       '^GLOSS|n|a brief explanation of a word; a shine|Both senses are real, and GLOSSARY comes from the first. Looks doubled up.',
       '*PENCRANT'],
      'PENCRANT looks like a stationery-trade term, and the invention hides beside a completely familiar object.',
      'GLOSS is the decoy: two unrelated-seeming senses, both legitimate, which makes players suspect one is invented.'],
    [2, 'mixed',
      ['PAPER|n|material made in thin sheets for writing', 'SMUDGY|adj|blurred or smeared', 'BIND|v|to fasten or tie together',
       '^RECTO|n|the right-hand page of an open book|Printing vocabulary; its partner is VERSO. Looks like invented Latin.',
       '*PAPRANT'],
      'PAPRANT looks like a papermaking term, and the shortened stem makes an invented word feel older than it is.',
      'RECTO is the trap: standard publishing vocabulary that reads as fabricated Latin.'],
    [3, 'mixed',
      ['MARGIN|n|the blank border of a page; a spare amount', 'DOGEARED|adj|worn with folded page corners', 'PROOF|n|a trial print for correction',
       '^COLOPHON|n|a publisher’s emblem or a note at the end of a book|Genuine printing vocabulary. Looks like invented Greek.',
       '*MARGRANT'],
      'MARGRANT looks like a printing or typographic term, and the round’s subject matter makes it feel plausible.',
      'COLOPHON is the decoy: a real and rather beautiful publishing word that looks manufactured.'],
    [3, 'visual-family',
      ['MARBLE|n|a hard crystalline rock used in sculpture', 'WARBLE|v|to sing with a trilling quality', 'GARBLE|v|to reproduce a message confusingly',
       '^BARBEL|n|a freshwater fish; a whisker-like organ on a fish|Both senses are real. Beside its rhymes it looks like the invention.',
       '*NARBLE'],
      'NARBLE hides among genuine -ARBLE words, and the pattern makes any further inspection feel unnecessary.',
      'BARBEL is the decoy: real in angling and in zoology, but it looks like a mistyping of BARBEL’s rhymes.'],
    [3, 'mixed',
      ['SERIF|n|a small stroke finishing a letter’s stem', 'BLOTCHY|adj|covered with irregular patches', 'EMBOSS|v|to carve a raised design on a surface',
       '^KERN|n|the space adjustment between two letters|Typographic vocabulary, also a verb. Looks like an abbreviation or a name.',
       '*SERIFANT'],
      'SERIFANT looks like a typographic term, and it borrows its stem from a real one in the same round.',
      'KERN is the trap: genuine typesetting vocabulary that reads as a surname or an acronym.'],
    [3, 'mixed',
      ['INKWELL|n|a small container for ink', 'RASPING|adj|harsh and grating in sound', 'STAPLE|n|a basic item; a fastener for paper',
       '^QUOIN|n|an external corner stone of a wall|Masonry vocabulary, pronounced "coin". Looks like a misspelling of COIN or GROIN.',
       '*INKRANT'],
      'INKRANT looks like a printing-industry term, and the compact shape makes it feel like trade shorthand.',
      'QUOIN is the decoy: a real building term whose spelling is genuinely at war with its pronunciation.'],
    [4, 'mixed',
      ['PALIMPSEST|n|a manuscript reused after erasing earlier writing', 'SNAFU|n|a confused or botched situation', 'GRANDILOQUENT|adj|pompous in language',
       '^FOOLSCAP|n|a large size of writing paper|A genuine paper size, from an old watermark. Looks like invented whimsy.',
       '*PALIMPSANT'],
      'PALIMPSANT keeps a real Greek root and takes -ANT, so it looks like a specialist adjective from manuscript studies.',
      'FOOLSCAP is the trap: a real paper size whose name sounds like something a novelist made up.'],
    [4, 'mixed',
      ['PERUSE|v|to read carefully; loosely, to skim', 'INTERLEAVE|v|to insert pages or elements between others', 'ERRATUM|n|a correction of a printing error',
       '^SIGNATURE|n|a printed sheet folded to form book pages|Beyond a name, it is a real bookbinding unit. That second sense looks invented.',
       '*PERUSANT'],
      'PERUSANT applies -ANT to a familiar verb, exactly as English produced CLAIMANT and APPLICANT.',
      'SIGNATURE is the decoy: everyone knows the word, but almost nobody knows its bookbinding sense, so the round feels like a trick.'],
    [5, 'mixed',
      ['INCUNABULA|n|books printed before 1501', 'OBLOQUY|n|strong public criticism or verbal abuse', 'DECKLE|n|a frame that fixes the size of a sheet of paper',
       '^FASCICLE|n|one instalment of a book published in parts|Genuine publishing vocabulary, also used in botany and anatomy. Looks invented.',
       '*INCUNABANT'],
      'INCUNABANT keeps the real root of INCUNABULA and takes -ANT, which in a round of specialist book vocabulary looks entirely at home.',
      'FASCICLE is the trap: a real term in publishing, botany and anatomy that reads like a diminutive someone coined.'],
  ],
});

export const GAMES_16_20 = [GAME_016, GAME_017, GAME_018, GAME_019, GAME_020];
