/**
 * PERKUL — daily games #006–#010 (2026-08-02 → 2026-08-06)
 */
import { buildGame } from './format';

export const GAME_006 = buildGame({
  date: '2026-08-02',
  gameNumber: 6,
  rounds: [
    [1, 'mixed',
      ['SADDLE|n|a seat for a rider', 'GLISTEN|v|to shine with reflected light', 'CROUCH|v|to lower the body close to the ground',
       '^SWATHE|n|a broad strip or area|"A swathe of countryside", also to wrap in bandages. The -THE ending looks improvised.',
       '*SADDRANT'],
      'SADDRANT looks like veterinary or equestrian vocabulary, and the -ANT ending gives any stem an official appearance.',
      'SWATHE is the trap: a common journalistic noun whose spelling looks like SWATH with a stray E added.'],
    [2, 'mixed',
      ['BRAMBLE|n|a prickly shrub, especially a blackberry', 'HINGE|n|a joint on which a door swings', 'SODDEN|adj|soaked through',
       '^CLEAVE|v|to split, or to cling closely|Remarkably, it means both to sever and to stick fast. That contradiction makes it feel invented.',
       '*BRAMBRIC'],
      'BRAMBRIC follows the -IC pattern of technical adjectives and keeps a familiar plant stem, so it looks catalogued rather than coined.',
      'CLEAVE is doubted because its two meanings are opposites; players assume one of them, or the word itself, must be fabricated.'],
    [2, 'mixed',
      ['SPECKLE|n|a small spot or patch of colour', 'JOSTLE|v|to push roughly against', 'FOLLY|n|foolishness; a costly ornamental building',
       '^WIZENED|adj|shrivelled with age|"A wizened face." It looks like a made-up participle of WIZARD.',
       '*SPECKRAL'],
      'SPECKRAL is one letter from SPECTRAL and shares SPECKLE’s stem, so it reads as a real word half-remembered.',
      'WIZENED is the decoy: entirely standard, yet its resemblance to WIZARD makes players suspect a joke.'],
    [3, 'mixed',
      ['SCAFFOLD|n|a temporary structure for workers', 'GRIME|n|ingrained dirt', 'HUSTLE|v|to push or hurry along',
       '^PITH|n|the soft core of a stem; the essential part|"The pith of the argument." Four letters, and easily read as a fragment of PITHY.',
       '*SCAFFRANT'],
      'SCAFFRANT reads like construction jargon, the kind of noun you assume exists somewhere in a standards document.',
      'PITH is the trap: real, and the parent of the far commoner PITHY, so the bare noun looks stripped down.'],
    [3, 'mixed',
      ['DAUNT|v|to intimidate or discourage', 'BUCKET|n|a cylindrical open container', 'SNARL|v|to growl with bared teeth',
       '^GAMBOL|v|to run or jump about playfully|Lambs gambol. It looks like a misspelling of GAMBLE, which is exactly the trap.',
       '*DAUNTREL'],
      'DAUNTREL borrows the -REL of SCOUNDREL and attaches it to a real verb, producing a very convincing noun.',
      'GAMBOL is doubted because everyone knows GAMBLE, and one of the two must be wrong — except neither is.'],
    [3, 'visual-family',
      ['MUSTER|v|to assemble, or to summon up', 'FLUSTER|v|to make agitated and confused', 'LUSTER|n|a gentle sheen or glow',
       '^BLUSTER|v|to talk loudly with empty threats|Wind blusters; so do bullies. Beside the others it looks like the odd invention.',
       '*GLUSTER'],
      'GLUSTER is hidden by four genuine -USTER words; the pattern makes examination feel unnecessary.',
      'BLUSTER is the decoy: real and common in speech, but the family setting makes players doubt the least concrete member.'],
    [3, 'mixed',
      ['TREACLE|n|thick dark syrup', 'FLINT|n|a hard grey stone that sparks when struck', 'FLANK|n|the side of the body or an army',
       '^SPRIG|n|a small shoot or twig|"A sprig of rosemary." One syllable, so it reads like a nickname or an invention.',
       '*TREACRANT'],
      'TREACRANT sounds close to RECREANT and TRENCHANT, both real, so the ear supplies the missing legitimacy.',
      'SPRIG is the trap: an ordinary cookery and gardening noun that looks fabricated when isolated.'],
    [4, 'mixed',
      ['FORAY|n|a sudden attack; a brief venture', 'DILATORY|adj|slow; tending to delay', 'CRAG|n|a steep rugged rock face',
       '^SPLAY|v|to spread out awkwardly|"Splayed fingers." Short, odd-looking, and easy to mistake for SPRAY or PLAY.',
       '*FORAYANT'],
      'FORAYANT looks like a military or legal term; the -ANT ending on a familiar noun almost always reads as real.',
      'SPLAY is the decoy because it looks like a typographic accident, though it is standard in anatomy and carpentry.'],
    [4, 'mixed',
      ['PENURY|n|extreme poverty', 'SHARD|n|a sharp fragment of glass or pottery', 'ABATE|v|to become less intense',
       '^VENAL|adj|open to bribery; corruptible|"A venal official." One letter from VENIAL, which means something quite different.',
       '*PENURANT'],
      'PENURANT uses the real root of PENURY with -ANT, so it looks like a legal adjective for the impoverished.',
      'VENAL is the trap: both VENAL and VENIAL are real, so players convince themselves one must have been invented.'],
    [5, 'mixed',
      ['LACONIC|adj|using very few words', 'TRUCULENT|adj|eager to argue or fight', 'EBB|v|to recede, as the tide does',
       '^SUPINE|adj|lying face upward; failing to act|"A supine response to the crisis." It looks like a variant of SUPPLY or SPINE.',
       '*LACONANT'],
      'LACONANT keeps the true stem of LACONIC and adds a common adjectival ending, so it looks properly derived rather than invented.',
      'SUPINE is the decoy: a real adjective with two quite different senses, and a shape that reads like an assembled word.'],
  ],
});

export const GAME_007 = buildGame({
  date: '2026-08-03',
  gameNumber: 7,
  rounds: [
    [1, 'mixed',
      ['FEATHER|n|one of the light structures covering a bird', 'GARLAND|n|a wreath of flowers or leaves', 'SCRUB|v|to rub hard to clean',
       '^HUSK|n|the dry outer covering of a seed|Also a verb, and figuratively a hollow remainder. Four letters, blunt, easily doubted.',
       '*FEATHRANT'],
      'FEATHRANT looks like a term from ornithology; unfamiliar -ANT nouns are usually real technical vocabulary.',
      'HUSK is the trap: entirely ordinary, but short enough to look like a fragment rather than a word.'],
    [2, 'mixed',
      ['MEDDLE|v|to interfere in something not one’s concern', 'CRATER|n|a large hollow caused by an impact', 'SLENDER|adj|gracefully thin',
       '^WROUGHT|adj|beaten or shaped by hammering|"Wrought iron", and an old past tense of WORK. The -OUGHT spelling looks absurd.',
       '*MEDDRANT'],
      'MEDDRANT sits close to the real MORDANT and PEDANT, which gives an invented word two respectable neighbours.',
      'WROUGHT is doubted because it looks like a spelling accident, yet it survives in everyday phrases such as wrought iron.'],
    [2, 'visual-family',
      ['HUMBLE|adj|modest; not proud', 'FUMBLE|v|to handle clumsily', 'JUMBLE|n|an untidy mixture',
       '^TUMBREL|n|an open cart, especially one carrying prisoners|The cart that carried the condemned in revolutionary France. Looks fabricated beside its rhymes.',
       '*SPUMBLE'],
      'SPUMBLE is protected by three unarguable -UMBLE words, and the SP- opening is a legal English cluster.',
      'TUMBREL is the decoy: a real historical noun that looks like a mangled TUMBLE.'],
    [3, 'mixed',
      ['SEVERANCE|n|the ending of a connection or contract', 'PRIM|adj|stiffly formal and proper', 'RAVAGE|v|to devastate',
       '^SCION|n|a descendant of a notable family|Also a shoot for grafting. The SC- opening with a long I looks impossible.',
       '*PRIMULENT'],
      'PRIMULENT resembles CORPULENT and OPULENT, and its stem looks Latin, so it reads like a formal adjective.',
      'SCION is the trap: standard in business journalism, but its spelling gives no clue to its pronunciation.'],
    [3, 'mixed',
      ['RUCKUS|n|a noisy disturbance or commotion', 'HEIRLOOM|n|a valuable object passed down in a family', 'PROD|v|to poke with a finger or object',
       '^WHELP|n|a young dog; a young man, contemptuously|A puppy, and an insult. WH- plus -ELP looks like a coinage.',
       '*CLATTRANT'],
      'CLATTRANT looks like a word from acoustics or music, and the -ANT ending disguises the invention completely.',
      'WHELP is the decoy: genuine, but its two senses are both slightly archaic, so it feels invented for effect.'],
    [3, 'mixed',
      ['SMELT|v|to extract metal from ore by heating', 'BRAWN|n|physical strength', 'TOPPLE|v|to fall or cause to fall over',
       '^SEDGE|n|a grass-like plant of wet ground|Common on riverbanks and in poetry. Looks like a blend of SEDGE’s neighbours HEDGE and LEDGE.',
       '*BRAWNTLE'],
      'BRAWNTLE combines a real noun with the -TLE of MANTLE and BRISTLE, giving it a solid, physical, English feel.',
      'SEDGE is the trap: an accurate botanical noun that reads as an invented cousin of HEDGE and LEDGE.'],
    [3, 'mixed',
      ['PILFER|v|to steal small amounts', 'GABLE|n|the triangular upper part of a wall', 'SCORCH|v|to burn the surface slightly',
       '^AVER|v|to state or assert to be true|"He averred that he had never met her." Four letters, chiefly legal, so it looks clipped.',
       '*PILFRANT'],
      'PILFRANT reads like a legal term for a petty thief, which is exactly the kind of word players assume exists.',
      'AVER is the decoy: real and current in court reporting, but easy to read as an abbreviation of AVERAGE.'],
    [4, 'mixed',
      ['REDOLENT|adj|strongly reminiscent or suggestive', 'GRAFT|n|hard work; a transplanted piece of tissue', 'SPARTAN|adj|austere and without comfort',
       '^NOISOME|adj|extremely unpleasant, especially in smell|Nothing to do with noise: it comes from ANNOY. That mismatch makes it feel invented.',
       '*REDOLANT'],
      'REDOLANT is a single vowel away from REDOLENT, so a player who knows the real word may believe this is the correct spelling.',
      'NOISOME is the trap: a legitimate adjective whose obvious-looking derivation from NOISE is completely wrong.'],
    [4, 'mixed',
      ['OBDURATE|adj|stubbornly refusing to change', 'THRESH|v|to separate grain by beating', 'VAUNTED|adj|boasted about, often undeservedly',
       '^SEEMLY|adj|proper; in good taste|The positive of UNSEEMLY, which is far more common. Looks like the puzzle removed a prefix.',
       '*OBDURANT'],
      'OBDURANT shares its root with OBDURATE and ends like ABUNDANT, making it look like the noun form of a familiar adjective.',
      'SEEMLY is the decoy: real, but so overshadowed by UNSEEMLY that players assume the bare form was manufactured.'],
    [5, 'mixed',
      ['ASSIDUOUS|adj|showing great care and perseverance', 'PROBITY|n|complete honesty and integrity', 'INVEIGH|v|to protest strongly',
       '^MOIETY|n|a half; a portion or share|Chiefly legal and anthropological. Long, French-looking and easy to reject as invented.',
       '*ASSIDUANCE'],
      'ASSIDUANCE takes a genuine adjective and applies -ANCE, the same route that produced ENDURANCE. Nothing about it looks wrong.',
      'MOIETY is the trap: a real term used in property law and anthropology that reads like a coinage from thin air.'],
  ],
});

export const GAME_008 = buildGame({
  date: '2026-08-04',
  gameNumber: 8,
  rounds: [
    [1, 'mixed',
      ['CHIMNEY|n|a vertical passage carrying smoke away', 'SPARKLE|v|to shine with flashes of light', 'GRUMBLE|v|to complain in a low voice',
       '^DELL|n|a small wooded valley|A little valley, chiefly poetic. Four letters and easily read as a name.',
       '*CHIMNAL'],
      'CHIMNAL applies the -AL ending that turns nouns into adjectives, so it reads like architectural vocabulary.',
      'DELL is the trap: a real landscape noun that now reads as a personal or company name.'],
    [2, 'mixed',
      ['TREMBLE|v|to shake involuntarily', 'PORCH|n|a covered entrance to a building', 'GLAZE|v|to cover with a glossy coating',
       '^BRINK|n|the extreme edge of something|"On the brink of collapse." Blunt and short, so it looks like slang.',
       '*TREMBRIC'],
      'TREMBRIC looks like a medical adjective; -IC on an unfamiliar stem is the commonest disguise a fake can wear.',
      'BRINK is the decoy: entirely standard, but its shape suggests a truncation of something longer.'],
    [2, 'mixed',
      ['SPINDLE|n|a slender rod used in spinning', 'MURMUR|v|to speak very softly', 'CHAFF|n|husks separated from grain; worthless matter',
       '^SWARD|n|an expanse of short grass|"A grassy sward." One letter from SWORD, which is why players reject it.',
       '*SPINDRANT'],
      'SPINDRANT reads like a textile or engineering term, and its stem is a real object, so it passes inspection easily.',
      'SWARD is the trap: a legitimate word for turf that looks like a misspelling of SWORD.'],
    [3, 'mixed',
      ['FRUGAL|adj|sparing with money or food', 'CLAMBER|v|to climb using hands and feet', 'RASP|v|to scrape harshly',
       '^WROTH|adj|extremely angry|Related to WRATH; "he was wroth". Looks like WORTH with letters transposed.',
       '*FRUGANT'],
      'FRUGANT joins the real stem of FRUGAL to -ANT, and English is full of adjectives built exactly that way.',
      'WROTH is the decoy: correct but heavily literary, and an easy read as a typo for WORTH or WRATH.'],
    [3, 'mixed',
      ['STARK|adj|severe or bare; sharply evident', 'PLIGHT|n|a dangerous or difficult situation', 'RUMPLE|v|to make untidy or creased',
       '^KEN|n|range of knowledge or sight|"Beyond my ken." Three letters and identical to a first name.',
       '*STARKLE'],
      'STARKLE looks like a frequentative of STARK in the same way SPARKLE relates to SPARK, so the derivation feels automatic.',
      'KEN is the trap: a genuine noun (and Scots verb) that is indistinguishable in print from a common name.'],
    [3, 'mixed',
      ['GRAVITAS|n|dignity and seriousness of manner', 'WEDLOCK|n|the state of being married', 'SMIRK|v|to smile smugly',
       '^ANODYNE|adj|inoffensive to the point of dullness|Also a noun for a painkiller. It looks like invented pharmaceutical branding.',
       '*WEDLANT'],
      'WEDLANT looks like an old legal term for marriage, and legal English really does contain words of that shape.',
      'ANODYNE is the decoy: standard in criticism, yet it reads like a drug name someone made up.'],
    [3, 'mixed',
      ['TENDRIL|n|a slender coiling shoot of a plant', 'BLURT|v|to say suddenly without thinking', 'GAUNT|adj|thin and bony from illness or hunger',
       '^CHIDE|v|to scold or rebuke mildly|"She chided him for being late." One letter from CHILD, and rare in speech.',
       '*TENDRANT'],
      'TENDRANT sits between TENANT and TENDRIL, borrowing the shape of one and the stem of the other.',
      'CHIDE is the trap: correct and still used in print, but its similarity to CHILD makes players read it as a slip.'],
    [4, 'mixed',
      ['INSIPID|adj|lacking flavour or interest', 'BULWARK|n|a defensive wall; a protection', 'FLIT|v|to move swiftly and lightly',
       '^SHRIFT|n|confession to a priest; "short shrift"|Survives almost entirely in "short shrift", so the bare noun looks invented.',
       '*BULWARANT'],
      'BULWARANT looks like a fortification term, and the -ANT ending is doing the same work here that it does in real jargon.',
      'SHRIFT is the decoy: a genuine noun trapped inside one idiom, which is exactly the profile of a fabricated word.'],
    [4, 'visual-family',
      ['TANGLE|v|to twist together confusingly', 'MANGLE|v|to mutilate by crushing or tearing', 'JANGLE|v|to make a harsh ringing noise',
       '^WRANGLE|n|a long complicated dispute|A noisy argument, also to herd cattle. Looks like the fabricated one in a row of rhymes.',
       '*DRANGLE'],
      'DRANGLE is camouflaged by four real -ANGLE words, where the shared ending removes all suspicion.',
      'WRANGLE is the decoy: real, but the silent W makes it look like an invention when set beside its plainer rhymes.'],
    [5, 'mixed',
      ['INTRANSIGENT|adj|refusing to compromise', 'PELLUCID|adj|translucently clear', 'DEMUR|v|to raise doubts or object',
       '^HALCYON|adj|idyllically calm and happy|"Halcyon days", from a mythical bird. Looks like invented poetic vocabulary.',
       '*PELLUCENT'],
      'PELLUCENT is a hair from PELLUCID and echoes TRANSLUCENT, so it looks like the version you half-remember.',
      'HALCYON is the trap: a legitimate adjective kept alive by one phrase, and its spelling gives players every excuse to doubt it.'],
  ],
});

export const GAME_009 = buildGame({
  date: '2026-08-05',
  gameNumber: 9,
  rounds: [
    [1, 'mixed',
      ['HARVEST|n|the gathering of crops', 'BUBBLE|n|a thin sphere of liquid enclosing air', 'STIFF|adj|rigid; not easily bent',
       '^LOAM|n|fertile soil of clay, sand and humus|Gardeners’ soil. Four letters and vowel-heavy, so it looks fabricated.',
       '*HARVANT'],
      'HARVANT looks like an agricultural term of long standing, and -ANT on a familiar stem rarely triggers suspicion.',
      'LOAM is the trap: a precise, useful soil noun that reads like an invented syllable.'],
    [2, 'mixed',
      ['SPUTTER|v|to make a series of soft explosive sounds', 'HARBOR|n|a sheltered place for ships', 'MEEK|adj|quiet, gentle and submissive',
       '^DELVE|v|to dig; to research deeply|"Delve into the archives." It looks like a blend of DELL and SHELVE.',
       '*CRACKRANT'],
      'CRACKRANT reads like an engineering term for a fault, and the invented word is doing nothing English does not already do.',
      'DELVE is the decoy: entirely current, yet unusual enough in form to look manufactured.'],
    [2, 'mixed',
      ['SHUDDER|v|to tremble convulsively', 'PILLAR|n|a tall vertical support', 'SOGGY|adj|unpleasantly wet and soft',
       '^GLIB|adj|fluent but insincere|"A glib answer." Four letters that look like an acronym or a nickname.',
       '*SHUDDRAL'],
      'SHUDDRAL uses the -AL of ordinary adjective formation on a familiar verb, so it reads as clinical vocabulary.',
      'GLIB is the trap: common in criticism, but so short and odd-looking that players suspect it in a hurry.'],
    [3, 'mixed',
      ['QUARRY|n|a place stone is cut from; a hunted animal', 'STOKE|v|to add fuel to a fire; to encourage', 'BLEAK|adj|bare and exposed; unpromising',
       '^SLATTERN|n|an untidy or slovenly woman|Dated and disapproving, but genuinely recorded. Looks like a blend of SLATE and PATTERN.',
       '*QUARRANT'],
      'QUARRANT looks like a surveying or heraldic term, and the double R makes it feel established.',
      'SLATTERN is the decoy: a real, if old-fashioned, noun that reads like a word invented from SLOVENLY and PATTERN.'],
    [3, 'visual-family',
      ['TATTER|n|a torn and hanging piece of cloth', 'PATTER|n|rapid continuous talk', 'SPATTER|v|to scatter in drops',
       '^CLATTER|n|a continuous rattling noise|A loud confused noise of hard objects. In a row of rhymes it looks like the invention.',
       '*SNATTER'],
      'SNATTER hides among four genuine -ATTER words, and the SN- opening is entirely ordinary in English.',
      'CLATTER is the decoy here: real and common, but the family pattern encourages players to distrust whichever one they read last.'],
    [3, 'mixed',
      ['CANDID|adj|truthful and straightforward', 'TROUGH|n|a long open container; a low point', 'WILT|v|to droop from heat or lack of water',
       '^SUFFUSE|v|to spread gradually through or over|"Light suffused the room." The double F and -USE ending look assembled.',
       '*CANDROLENT'],
      'CANDROLENT looks like a chemical or medical adjective, and length plus -ENT is a powerful disguise.',
      'SUFFUSE is the trap: a real and rather beautiful verb that looks like a technical invention.'],
    [3, 'mixed',
      ['MASONRY|n|stonework', 'SCOFF|v|to speak with scornful derision', 'CLAMMY|adj|unpleasantly damp and sticky',
       '^SPELT|n|an ancient variety of wheat|Also a past tense of SPELL, which is the confusion. As a grain it looks fabricated.',
       '*MASONANT'],
      'MASONANT reads like a building-trade term, and it sits beside a real noun that shares its stem.',
      'SPELT is the decoy: a genuine grain now common in bakeries, but most players read it only as a verb form.'],
    [4, 'mixed',
      ['ELEGY|n|a mournful poem, especially for the dead', 'RESOLUTE|adj|admirably determined', 'CHAFE|v|to rub and make sore; to irritate',
       '^COMELY|adj|pleasant to look at|"A comely figure." The -ELY ending on COME looks like an error.',
       '*ELEGRANT'],
      'ELEGRANT is one letter from ELEGANT and shares a stem with ELEGY, so players read it as a formal literary term they simply cannot place.',
      'COMELY is the trap: a legitimate if old-fashioned adjective that reads like an adverb built by mistake.'],
    [4, 'mixed',
      ['PARLANCE|n|a particular way of using words', 'BROACH|v|to raise a subject; to pierce a container', 'STINT|n|a fixed period of work',
       '^SANGUINARY|adj|involving much bloodshed|Not to be confused with SANGUINE, which means cheerful. The pair looks like a trick.',
       '*PARLANT'],
      'PARLANT looks like a legal or musical term of French descent, and PARLANCE beside it supplies the missing credibility.',
      'SANGUINARY is the decoy: real, and so close to SANGUINE that players assume one of the two was invented.'],
    [5, 'mixed',
      ['PERFIDY|n|deliberate betrayal of trust', 'LUCUBRATION|n|laborious study or writing', 'ABJURE|v|to renounce solemnly',
       '^FEALTY|n|a sworn loyalty to a lord|Feudal in origin, still used figuratively. Looks like a blend of FEAL and LOYALTY.',
       '*PERFIDANT'],
      'PERFIDANT uses the real root of PERFIDY with -ANT, so it looks like the word for a person who betrays.',
      'FEALTY is the trap: a genuine noun still used in political writing, whose spelling looks like an invented contraction.'],
  ],
});

export const GAME_010 = buildGame({
  date: '2026-08-06',
  gameNumber: 10,
  rounds: [
    [1, 'mixed',
      ['WHISPER|v|to speak very softly', 'PADDLE|n|a short oar with a broad blade', 'FROSTY|adj|very cold; unfriendly',
       '^SCANTLING|n|a small timber beam of standard size|Builders’ vocabulary for a sized piece of timber. Looks like SCANT plus a suffix invented for the puzzle.',
       '*WHISPRANT'],
      'WHISPRANT looks like an acoustics term, and dropping the E in WHISPER makes it feel like a proper Latinate derivation.',
      'SCANTLING is the trap: a real building term that looks exactly like a fabricated diminutive of SCANT.'],
    [2, 'mixed',
      ['SPROCKET|n|a toothed wheel that engages a chain', 'BLUSH|v|to redden in the face', 'HOLLY|n|an evergreen shrub with red berries',
       '^ROWEL|n|the spiked wheel on a spur|The revolving spike on a rider’s spur. Two syllables that look like a mangled TOWEL.',
       '*SPROCKANT'],
      'SPROCKANT reads like mechanical vocabulary, and machinery is full of genuinely strange -ANT and -ET words.',
      'ROWEL is the decoy: a legitimate piece of equestrian equipment that looks like a typo for ROWEL’s neighbours TOWEL and VOWEL.'],
    [2, 'mixed',
      ['SHINGLE|n|a thin roof tile; coarse beach pebbles', 'GROAN|v|to make a low sound of pain', 'TIDY|adj|arranged neatly',
       '^SWILL|v|to rinse; to drink greedily|Also pig feed. Short, unattractive and easily mistaken for an invention.',
       '*SHINGRANT'],
      'SHINGRANT looks like a roofing or dermatological term, both fields that produce genuinely odd vocabulary.',
      'SWILL is the trap: three plain senses, all real, in a word that looks coined for comic effect.'],
    [3, 'mixed',
      ['LEDGER|n|a book of financial accounts', 'PRUNE|v|to trim branches; to cut back', 'BRISK|adj|quick and energetic',
       '^ARRANT|adj|complete; utter, in a bad sense|"Arrant nonsense." One letter from ERRANT, with a different meaning.',
       '*LEDGRANT'],
      'LEDGRANT looks like an accountancy term, and it is only two letters from the real ARRANT sitting in the same round.',
      'ARRANT is the decoy: genuine and precise, but nearly identical to ERRANT, so players assume one is fabricated.'],
    [3, 'mixed',
      ['CHISEL|n|a tool with a bevelled cutting edge', 'FLUSTERED|adj|agitated and confused', 'MEASLY|adj|contemptibly small',
       '^QUIRE|n|a set of sheets of paper folded together|A bookbinding unit, and the origin of CHOIR’s spelling confusion. Looks like a misprint.',
       '*CHISRANT'],
      'CHISRANT sounds like a tool-making term, and losing the vowel from CHISEL makes the coinage look older, not newer.',
      'QUIRE is the trap: a real printing and bookbinding noun that reads as a misspelling of CHOIR.'],
    [3, 'mixed',
      ['SALVAGE|v|to rescue from loss or destruction', 'PRICKLE|n|a small thorn; a tingling sensation', 'DINGY|adj|gloomy and dirty',
       '^WELKIN|n|the sky or heavens|"Make the welkin ring." Literary, and it looks like an invented compound.',
       '*SALVRANT'],
      'SALVRANT looks like insurance or maritime vocabulary, exactly the register where unfamiliar real words live.',
      'WELKIN is the decoy: genuinely recorded and used in literary English, but so rare that players read it as a fabrication.'],
    [3, 'visual-family',
      ['BOTTLE|n|a container with a narrow neck', 'MOTTLE|v|to mark with blotches of colour', 'THROTTLE|v|to choke; to control fuel flow',
       '^WATTLE|n|interwoven sticks; the flesh under a bird’s beak|Wattle-and-daub walls, and a turkey’s wattle. Looks like the invented member.',
       '*GOTTLE'],
      'GOTTLE is protected by four genuine -OTTLE words, and the pattern makes checking feel unnecessary.',
      'WATTLE is the decoy: two real and quite different senses, in a word that looks like a nonsense rhyme.'],
    [4, 'mixed',
      ['AUSTERE|adj|severe or plain; without comfort', 'RUE|v|to regret bitterly', 'MAWKISH|adj|sentimental in a feeble way',
       '^SUNDRY|adj|of various kinds|"Sundry items." Looks like a compound of SUN and DRY, which is nonsense.',
       '*AUSTRANT'],
      'AUSTRANT looks like a geographical or legal adjective, and the AUST- opening is shared with real words.',
      'SUNDRY is the trap: standard in invoices and inventories, but its apparent parts make no sense, so it looks assembled.'],
    [4, 'mixed',
      ['PROSAIC|adj|dull and unimaginative', 'TRUSS|n|a framework of beams; a support', 'TERSE|adj|brief and to the point, sometimes curtly so',
       '^RECREANT|adj|cowardly; unfaithful|A real if literary adjective for a coward or traitor. Looks like an invented cousin of RECREATE.',
       '*PROSANT'],
      'PROSANT looks like a literary-critical term, and it shares its stem with PROSE and PROSAIC in the same round.',
      'RECREANT is the decoy: legitimate, but its resemblance to RECREATION makes it look like a fabricated derivative.'],
    [5, 'mixed',
      ['INEFFABLE|adj|too great to be expressed in words', 'CUPIDITY|n|greed for money or possessions', 'GAINSAY|v|to deny or contradict',
       '^SUBORN|v|to bribe someone to commit an offence|"Suborn a witness." Looks like a mangled form of SUBURB or SUBORDINATE.',
       '*INEFFANT'],
      'INEFFANT keeps the real root of INEFFABLE and takes the -ANT ending, producing something that looks like a legal adjective.',
      'SUBORN is the trap: a precise legal verb that reads as an invented prefix experiment.'],
  ],
});

export const GAMES_06_10 = [GAME_006, GAME_007, GAME_008, GAME_009, GAME_010];
