/**
 * PERKUL — daily games #011–#015 (2026-08-07 → 2026-08-11)
 */
import { buildGame } from './format';

export const GAME_011 = buildGame({
  date: '2026-08-07',
  gameNumber: 11,
  rounds: [
    [1, 'mixed',
      ['ORCHARD|n|a plot planted with fruit trees', 'CLATTERING|adj|making a rattling noise', 'SNUG|adj|comfortably warm and close-fitting',
       '^BOLE|n|the trunk of a tree|The main stem of a tree. Four letters and identical in sound to BOWL, so it looks like an error.',
       '*ORCHRANT'],
      'ORCHRANT looks like a horticultural term of long standing, and the -ANT ending is the commonest disguise in this game.',
      'BOLE is the trap: precise forestry vocabulary that reads as a misspelling of BOWL or MOLE.'],
    [2, 'mixed',
      ['SHATTER|v|to break violently into pieces', 'FURNACE|n|an enclosed structure for intense heat', 'PLUCKY|adj|brave and determined',
       '^SLUG|n|a shell-less mollusc; a heavy blow; a slow person|Three distinct senses, all real, in four letters — which makes it feel like filler.',
       '*FURNANT'],
      'FURNANT resembles the real FORMANT and sits beside FURNACE, so the eye reads it as an industrial term.',
      'SLUG is the decoy: so short and so slangy that players assume it cannot be doing serious work in a puzzle.'],
    [2, 'mixed',
      ['GLOOMY|adj|dark or depressing', 'RATTLE|v|to make a rapid series of short knocks', 'CARVE|v|to cut into a shape',
       '^SPLICE|v|to join by interweaving or overlapping|Ropes, film and genes are all spliced. The SPL- opening looks invented.',
       '*GLOOMRANT'],
      'GLOOMRANT reads like a literary or meteorological coinage, and the compound shape makes it look documented.',
      'SPLICE is the trap: entirely standard in sailing, film and genetics, but visually strange enough to attract blame.'],
    [3, 'visual-family',
      ['SINGE|v|to burn slightly at the edges', 'TINGE|n|a slight trace of colour or feeling', 'FRINGE|n|a border of threads; the edge of something',
       '^CRINGE|v|to bend in fear or embarrassment|Now also slang for acute awkwardness. Beside its rhymes it looks like the odd invention.',
       '*PLINGE'],
      'PLINGE hides inside four genuine -INGE words, and the PL- cluster is completely ordinary in English.',
      'CRINGE is the decoy: real and current, but the family pattern encourages players to pick the one they last read.'],
    [3, 'mixed',
      ['BUTTRESS|n|a support built against a wall', 'GLUT|n|an excessive supply', 'HAZY|adj|misty; unclear',
       '^SLATE|v|to criticise severely|Beyond the rock and the roof tile, British usage means to review harshly. That third sense looks invented.',
       '*BUTTRANT'],
      'BUTTRANT looks like a term from masonry, and it shares its opening with a real architectural noun in the same round.',
      'SLATE is the trap: three senses, all legitimate, and the critical sense is unfamiliar to many players.'],
    [3, 'mixed',
      ['SCAFFOLDING|n|a temporary framework of poles and planks', 'REEK|v|to smell strongly and unpleasantly', 'SPRY|adj|active and nimble, especially when old',
       '^WHITHER|adv|to what place or state|"Whither the economy?" Constantly confused with WITHER, so it looks like a typo.',
       '*SPRYANT'],
      'SPRYANT looks like a rare adjective from an older register; -ANT lends respectability to almost any stem.',
      'WHITHER is the decoy: a genuine adverb still used in headlines, and one letter from a much commoner verb.'],
    [3, 'mixed',
      ['LOPSIDED|adj|uneven; heavier on one side', 'CHURN|v|to stir violently; to produce mechanically', 'MEDDLESOME|adj|inclined to interfere',
       '^SATE|v|to satisfy fully|"Sated with food." Four letters, and easily read as a misprint of SAFE or LATE.',
       '*CHURNANT'],
      'CHURNANT reads like a term from dairying or finance, and the -ANT ending makes an invention look catalogued.',
      'SATE is the trap: real, current, and short enough to look like a typing error.'],
    [4, 'mixed',
      ['PENCHANT|n|a strong liking for something', 'CALLOW|adj|inexperienced and immature', 'BRAZEN|adj|shamelessly bold',
       '^SURFEIT|n|an excessive amount|"A surfeit of choice." The -FEIT ending looks like it belongs to COUNTERFEIT and nothing else.',
       '*CALLANT'],
      'CALLANT is a legal-sounding noun built on a familiar stem, and it hides beside PENCHANT, which shares its ending.',
      'SURFEIT is the decoy: an excellent, real noun whose spelling looks borrowed from a different word entirely.'],
    [4, 'mixed',
      ['HAGGARD|adj|looking exhausted and unwell', 'WINSOME|adj|charmingly attractive', 'FOIST|v|to impose something unwelcome on someone',
       '^SULLY|v|to damage the purity or integrity of|"Sully a reputation." Two syllables with no obvious relatives, so it reads as invented.',
       '*WINSANT'],
      'WINSANT pairs the genuine WINSOME stem with -ANT, and it sits directly beside the real word to borrow its authority.',
      'SULLY is the decoy: a legitimate verb about reputation that most players have read but never written.'],
    [5, 'mixed',
      ['INTERSTICE|n|a small intervening space', 'RECONDITE|adj|obscure; understood by few', 'SLAKED|adj|satisfied or quenched',
       '^APOCRYPHAL|adj|widely circulated but probably untrue|Of a story: doubtful. Long, Greek-looking and easy to reject as invented.',
       '*RECONDANT'],
      'RECONDANT keeps RECONDITE’s stem and adds -ANT, so it looks like the adjective a specialist would use.',
      'APOCRYPHAL is the trap: entirely standard in journalism, but its length and Greek shape make it a natural suspect.'],
  ],
});

export const GAME_012 = buildGame({
  date: '2026-08-08',
  gameNumber: 12,
  rounds: [
    [1, 'mixed',
      ['BRIDLE|n|the headgear used to control a horse', 'SPLASH|v|to scatter liquid noisily', 'STURDY|adj|strongly built',
       '^SKEIN|n|a loose coil of yarn; a complex arrangement|"A skein of wool", "a skein of lies". The EI spelling looks impossible.',
       '*BRIDRANT'],
      'BRIDRANT looks like equestrian or engineering vocabulary, both fields where genuinely strange words survive.',
      'SKEIN is the trap: a real and useful noun whose spelling offers no help with its pronunciation.'],
    [2, 'mixed',
      ['GRAPPLING|adj|struggling at close quarters', 'MOSSY|adj|covered with moss', 'CROON|v|to sing or speak softly',
       '^SLOE|n|the small sour fruit of the blackthorn|The berry in sloe gin. Three letters, and identical in sound to SLOW.',
       '*MOSSANT'],
      'MOSSANT looks like a botanical adjective, and it borrows credibility from a plain noun in the same round.',
      'SLOE is the decoy: legitimate, and familiar only through one drink, so it reads as a misspelling of SLOW.'],
    [2, 'mixed',
      ['THRESHER|n|a machine that separates grain', 'DAMP|adj|slightly wet', 'HUDDLE|v|to crowd together closely',
       '^GAMY|adj|having the strong flavour of game|Also risqué. Looks like a misspelling of GAME with a stray Y.',
       '*THRESHANT'],
      'THRESHANT reads like agricultural machinery vocabulary, which is full of unfamiliar but genuine words.',
      'GAMY is the trap: a real culinary adjective that looks like a careless abbreviation.'],
    [3, 'mixed',
      ['LATTICE|n|a criss-crossed structure', 'PARRIED|adj|warded off, as a blow', 'GORSE|n|a yellow-flowered thorny shrub',
       '^SPOOR|n|the track or scent of an animal|Used by trackers and, figuratively, by journalists. Looks like a doubled-vowel invention.',
       '*LATTRANT'],
      'LATTRANT looks like an architectural or textile term, and the double T makes it feel long established.',
      'SPOOR is the decoy: entirely real, but its doubled O looks like a deliberate fabrication.'],
    [3, 'mixed',
      ['GRIDIRON|n|a metal grid for cooking over fire', 'WHIM|n|a sudden fanciful desire', 'FROTH|n|a mass of small bubbles',
       '^SLATTED|adj|made of narrow strips of wood|"Slatted blinds." Looks like a mistake for SLATED or SPLATTED.',
       '*FROTHANT'],
      'FROTHANT looks like a chemical additive, and industrial vocabulary genuinely contains words of this shape.',
      'SLATTED is the trap: a plain descriptive adjective that sits one letter from two other real words.'],
    [3, 'visual-family',
      ['BUDGE|v|to move slightly', 'SMUDGE|n|a blurred mark', 'GRUDGING|adj|given reluctantly',
       '^TRUDGE|v|to walk slowly and with effort|Heavy, tired walking. In a row of rhymes it looks like the invented one.',
       '*SPUDGE'],
      'SPUDGE is hidden by a family of real -UDGE words, and the SP- opening is completely ordinary English.',
      'TRUDGE is the decoy: real and common, but the pattern makes players distrust the least abstract member.'],
    [3, 'mixed',
      ['MANIFOLD|adj|many and various', 'SCUPPER|v|to sink deliberately; to ruin a plan', 'GRIMY|adj|covered with dirt',
       '^NOSTRUM|n|a dubious remedy or scheme|"Political nostrums." Latin-looking and easy to mistake for a brand of medicine.',
       '*MANIFRANT'],
      'MANIFRANT looks like a shipping or logistics term, and MANIFOLD beside it lends the stem authority.',
      'NOSTRUM is the trap: standard in political commentary, but it reads like the name of a cough syrup.'],
    [4, 'mixed',
      ['PARLOUS|adj|full of danger or uncertainty', 'THRUM|v|to make a low rhythmic hum', 'WAIF|n|a homeless or neglected person',
       '^ELIDE|v|to omit or merge, as in speech|Syllables are elided; so are difficult facts. Looks like a blend of ELUDE and SLIDE.',
       '*THRUMBLE'],
      'THRUMBLE joins the real verb THRUM to the -MBLE of RUMBLE and TUMBLE, one of the most productive endings in English.',
      'ELIDE is the decoy: a real linguistic verb that looks like a misprint of ELUDE.'],
    [4, 'mixed',
      ['INVEIGLE|v|to persuade by flattery or deception', 'STOLID|adj|calm and showing little emotion', 'CANT|n|insincere pious talk; jargon',
       '^SPECIOUS|adj|superficially plausible but wrong|"A specious argument." Looks like a cousin of SPECIAL or SPECIES.',
       '*STOLIDANT'],
      'STOLIDANT applies -ANT to a real adjective, which is how English produced words such as RESULTANT.',
      'SPECIOUS is the trap: essential critical vocabulary whose stem misleads players about its meaning.'],
    [5, 'mixed',
      ['OBSEQUIOUS|adj|excessively eager to please', 'TRENCHANT|adj|vigorous and incisive', 'ADUMBRATE|v|to outline or foreshadow',
       '^INCHOATE|adj|just begun; rudimentary and unformed|"Inchoate ideas." Nothing to do with CHAOS, though it looks as if it should be.',
       '*OBSEQUANT'],
      'OBSEQUANT keeps the true root of OBSEQUIOUS and takes -ANT, so it looks like a legal or ecclesiastical adjective.',
      'INCHOATE is the decoy: a real and precise adjective that looks like an invented relative of CHAOTIC.'],
  ],
});

export const GAME_013 = buildGame({
  date: '2026-08-09',
  gameNumber: 13,
  rounds: [
    [1, 'mixed',
      ['SATCHEL|n|a bag with a shoulder strap', 'FLOCK|n|a group of birds or sheep', 'DUSTY|adj|covered with dust',
       '^WICKET|n|a small gate or door; a set of cricket stumps|A little gate, and cricket’s target. Looks like a diminutive invented for the puzzle.',
       '*SATCHRANT'],
      'SATCHRANT looks like a leather-trade term, and traditional crafts are full of unfamiliar genuine words.',
      'WICKET is the trap: two entirely real senses in a word that reads like a made-up diminutive.'],
    [2, 'mixed',
      ['TROLLEY|n|a wheeled cart or vehicle', 'SPONGY|adj|soft and absorbent', 'CLASP|v|to grasp tightly',
       '^SEDULOUS|adj|showing dedicated diligence|"Sedulous attention to detail." Looks like a blend of SEDATE and CREDULOUS.',
       '*TROLLANT'],
      'TROLLANT looks like a transport or fishing term, and the double L makes the invention feel settled.',
      'SEDULOUS is the decoy: a real adjective of praise that appears to be assembled from two unrelated words.'],
    [2, 'mixed',
      ['GRANITE|n|a very hard igneous rock', 'PEEVISH|adj|irritable and querulous', 'DRAB|adj|dull and colourless',
       '^SHOAL|n|a school of fish; a shallow sandbank|Two senses, both nautical, both real. The -OAL ending looks arbitrary.',
       '*GRANITANT'],
      'GRANITANT reads like a geological term, and geology genuinely produces words that look like this.',
      'SHOAL is the trap: standard in fishing and navigation, but visually close to SHOAL’s unrelated neighbours SHOULD and SHAWL.'],
    [3, 'mixed',
      ['PALISADE|n|a fence of stakes for defence', 'SMATTERING|n|a slight superficial knowledge', 'CRUX|n|the decisive point at issue',
       '^SUCCINCT|adj|briefly and clearly expressed|Praise for concision. The double C and -INCT ending look invented.',
       '*PALISANT'],
      'PALISANT looks like a fortification or landscaping term, and its stem is a real defensive structure.',
      'SUCCINCT is the decoy: common in editing and business, but its spelling is genuinely peculiar.'],
    [3, 'mixed',
      ['VERDANT|adj|green with vegetation', 'SPURN|v|to reject with contempt', 'GRUELING|adj|extremely tiring and demanding',
       '^EYRIE|n|a large bird of prey’s nest, high up|Also spelled AERIE. Vowel-heavy and easy to reject as fabricated.',
       '*VERDANCE'],
      'VERDANCE applies -ANCE to a real adjective, exactly the route that produced RADIANCE and BRILLIANCE.',
      'EYRIE is the trap: a genuine noun with two accepted spellings, which makes players assume neither is right.'],
    [3, 'mixed',
      ['CATACOMB|n|an underground cemetery of galleries', 'WANE|v|to decrease in size or strength', 'GLOWER|v|to stare angrily',
       '^SEISMIC|adj|relating to earthquakes; hugely significant|Standard in geology and in politics. The EI spelling looks improbable.',
       '*CATACRANT'],
      'CATACRANT looks like an archaeological term, and long compound-looking words are rarely challenged.',
      'SEISMIC is the decoy: entirely familiar in speech, but its spelling looks fabricated on the page.'],
    [3, 'mixed',
      ['THRIFT|n|careful management of money', 'BEDRAGGLED|adj|dirty and dishevelled', 'PANG|n|a sudden sharp pain or emotion',
       '^SPLENDOR|n|magnificent appearance or grandeur|Ordinary in American spelling. Beside stranger words it can still look assembled.',
       '*THRIFTANT'],
      'THRIFTANT looks like a financial or actuarial term, and the -ANT ending makes it feel institutional.',
      'SPLENDOR is the decoy: unarguably real, which is the point — some rounds punish players for suspecting the ordinary.'],
    [4, 'visual-family',
      ['LITTER|n|rubbish left in a public place', 'TITTER|v|to laugh in a nervous, half-suppressed way', 'GLITTER|v|to shine with flashes of light',
       '^JITTER|n|slight irregular movement or nervousness|"The jitters", and a technical term for signal instability. Looks like the invention.',
       '*PRITTER'],
      'PRITTER is protected by four real -ITTER words; the pattern is doing all of the work.',
      'JITTER is the decoy: real in both casual and technical registers, but it looks like a nonsense rhyme here.'],
    [4, 'mixed',
      ['ACERBIC|adj|sharp and forthright in tone', 'MILIEU|n|a person’s social environment', 'DEFT|adj|neatly skilful and quick',
       '^BROMIDE|n|a trite remark; a sedative compound|"Comforting bromides." Chemistry and criticism share the word, which feels wrong.',
       '*ACERBANT'],
      'ACERBANT looks like a food-science term, and it shares its stem with a real adjective in the same round.',
      'BROMIDE is the trap: a genuine word in two unrelated fields, which makes players assume one usage is invented.'],
    [5, 'mixed',
      ['PUSILLANIMOUS|adj|showing a lack of courage', 'ANATHEMA|n|something detested or cursed', 'WIZEN|v|to shrivel or dry up',
       '^EPHEMERAL|adj|lasting a very short time|Standard in criticism and biology. Long and Greek-looking, so it attracts doubt.',
       '*PUSILLANT'],
      'PUSILLANT looks like a shortened but legitimate form of PUSILLANIMOUS, and shortened Latinate adjectives really do exist.',
      'EPHEMERAL is the decoy: entirely real and rather common, but its length and shape make it a soft target in a hard round.'],
  ],
});

export const GAME_014 = buildGame({
  date: '2026-08-10',
  gameNumber: 14,
  rounds: [
    [1, 'mixed',
      ['CUPBOARD|n|a piece of furniture with shelves and doors', 'MUDDY|adj|covered in wet earth', 'SNIP|v|to cut with small quick strokes',
       '^CLEAT|n|a wedge or projection used to secure a rope|On boats and boots. Four letters, and easily read as a mistake for CLEAN or PLEAT.',
       '*CUPBRANT'],
      'CUPBRANT looks like a joinery term, and the consonant cluster makes the invention feel old rather than new.',
      'CLEAT is the trap: real in sailing and in football boots, but visually adjacent to several commoner words.'],
    [2, 'mixed',
      ['BRAMBLES|n|prickly shrubs of the blackberry family', 'SIZZLE|v|to make a hissing sound when frying', 'TIMID|adj|lacking courage or confidence',
       '^DUNNAGE|n|loose packing material protecting cargo|Shipping vocabulary for padding in a hold. Looks like a blend of DUNGEON and BAGGAGE.',
       '*SIZZRANT'],
      'SIZZRANT looks like a food-industry term, and the doubled Z gives it a manufactured-but-official appearance.',
      'DUNNAGE is the decoy: a genuine logistics noun that most players have simply never met.'],
    [2, 'mixed',
      ['TROUSERS|n|an outer garment covering the legs', 'GLOSSY|adj|shiny and smooth', 'PROWL|v|to move stealthily in search of prey',
       '^SELVAGE|n|the finished edge of a piece of fabric|Textile vocabulary; also spelled SELVEDGE. Looks like a misspelling of SALVAGE.',
       '*PROWLANT'],
      'PROWLANT looks like a zoological adjective, and adding -ANT to a familiar verb is a standard English pattern.',
      'SELVAGE is the trap: a real textile term that sits one letter from SALVAGE, so players read it as a mistake.'],
    [3, 'mixed',
      ['CANOPY|n|an overhead covering', 'RIVULET|n|a very small stream', 'STOUT|adj|thickset; determined',
       '^ESCARPMENT|n|a long steep slope at the edge of a plateau|Geography vocabulary. Long enough that players suspect it was assembled.',
       '*CANOPANT'],
      'CANOPANT looks like a botanical term for forest structure, and the stem is a genuine noun.',
      'ESCARPMENT is the decoy: a precise geographical noun whose length makes it look invented in a hurry.'],
    [3, 'visual-family',
      ['GRAVELLY|adj|rough-sounding, like gravel', 'TRAVEL|v|to make a journey', 'GAVEL|n|a small mallet used by a judge or auctioneer',
       '^RAVEL|v|to fray, or to disentangle|Confusingly, it means both to tangle and to untangle, like UNRAVEL. Looks like the invention.',
       '*SNAVEL'],
      'SNAVEL hides in a family of real -AVEL words, and the SN- opening is entirely ordinary.',
      'RAVEL is the decoy: a real verb whose meaning contradicts itself, so players assume it was invented for the round.'],
    [3, 'mixed',
      ['FLOTSAM|n|floating wreckage or debris', 'GRUMPY|adj|bad-tempered', 'SCUFFLE|n|a short confused fight',
       '^JETSAM|n|goods deliberately thrown overboard|The companion of FLOTSAM: jettisoned cargo. Looks like the invented half of a pair.',
       '*FLOTRANT'],
      'FLOTRANT looks like a maritime or chemical term, and it shares its opening with a real noun in the same round.',
      'JETSAM is the trap: half of a very familiar phrase, but on its own it looks like a fabrication built to match FLOTSAM.'],
    [3, 'mixed',
      ['PARCHMENT|n|a writing surface made from animal skin', 'WOOZY|adj|dizzy and unsteady', 'GRAZE|v|to feed on grass; to scrape lightly',
       '^VELLUM|n|fine parchment made from calfskin|Used for important documents. Double L, Latin-looking, and easy to reject.',
       '*PARCHRANT'],
      'PARCHRANT looks like a conservation or printing term, and the stem is a real material in the same round.',
      'VELLUM is the decoy: a genuine material still used for formal documents, though it looks like invented Latin.'],
    [4, 'mixed',
      ['LUGUBRIOUS|adj|looking or sounding mournful', 'STANCH|v|to stop the flow of blood', 'PRIG|n|a self-righteously moralistic person',
       '^HUSTINGS|n|the proceedings of an election campaign|"Out on the hustings." Plural-looking and archaic in feel, so it reads as invented.',
       '*LUGUBRANT'],
      'LUGUBRANT keeps a real Latin root and takes -ANT, so it looks like a legitimate if bookish adjective.',
      'HUSTINGS is the trap: standard British political vocabulary that looks like a fabricated plural.'],
    [4, 'mixed',
      ['EQUIVOCATE|v|to use ambiguous language to conceal the truth', 'DOGGED|adj|persistent in effort', 'MAUDLIN|adj|self-pityingly sentimental',
       '^EMOLLIENT|adj|softening; soothing|A moisturiser is an emollient; so is a soothing remark. It looks like invented pharmacy vocabulary.',
       '*EQUIVANT'],
      'EQUIVANT looks like a legal or logical term, and the EQUI- opening is shared with several real words.',
      'EMOLLIENT is the decoy: real in both cosmetics and diplomacy, but it reads like a brand name.'],
    [5, 'mixed',
      ['PERSPICACIOUS|adj|having keen insight', 'BOWDLERIZE|v|to censor by removing offensive material', 'THRALL|n|the state of being in someone’s power',
       '^SUPERNAL|adj|celestial; of exceptional quality|The opposite of INFERNAL. Looks like a misprint of SUPERNATURAL.',
       '*PERSPICANT'],
      'PERSPICANT keeps the real root of PERSPICACIOUS and takes -ANT, so it looks like the concise version of a word you know.',
      'SUPERNAL is the trap: a genuine adjective, and clearly the sibling of INFERNAL, yet it reads as a truncation.'],
  ],
});

export const GAME_015 = buildGame({
  date: '2026-08-11',
  gameNumber: 15,
  rounds: [
    [1, 'mixed',
      ['WINDOW|n|an opening fitted with glass', 'CHUCKLE|v|to laugh quietly', 'SANDY|adj|covered with or resembling sand',
       '^SCREE|n|loose stones on a mountain slope|Hillwalkers’ vocabulary. Double E and four letters, so it looks fabricated.',
       '*WINDRANT'],
      'WINDRANT looks like a meteorological term, and readers assume weather science owns words they do not recognise.',
      'SCREE is the trap: precise mountaineering vocabulary that reads as a misspelling of SCREEN or SCREE’s neighbour FREE.'],
    [2, 'mixed',
      ['CARTON|n|a light cardboard box', 'FUZZY|adj|indistinct; covered with fine hairs', 'PLOD|v|to walk doggedly and slowly',
       '^TARN|n|a small mountain lake|Common in the Lake District and in poetry. Four letters and easily read as a name.',
       '*CARTRANT'],
      'CARTRANT looks like a packaging or logistics term, and the stem is an everyday object.',
      'TARN is the decoy: a genuine geographical noun that looks like an abbreviation or a surname.'],
    [2, 'visual-family',
      ['NETTLE|n|a plant with stinging leaves', 'SETTLE|v|to resolve; to come to rest', 'METTLE|n|courage and fortitude',
       '^KETTLEDRUM|n|a large drum with a hemispherical body|A real orchestral instrument, the timpani. Its compound shape looks improvised.',
       '*PRETTLE'],
      'PRETTLE is hidden by a family of real -ETTLE words, and the PR- opening is entirely ordinary.',
      'KETTLEDRUM is the decoy: a genuine instrument whose name looks like a joke assembled from two nouns.'],
    [3, 'mixed',
      ['ARCHIVE|n|a collection of historical documents', 'SEEP|v|to flow slowly through small openings', 'BLUNT|adj|not sharp; direct in speech',
       '^COPSE|n|a small group of trees|A little wood. Looks like a blend of CORPSE and COPS, which is unhelpful.',
       '*ARCHRANT'],
      'ARCHRANT looks like an architectural or archival term, and both fields legitimately contain words of this shape.',
      'COPSE is the trap: ordinary countryside vocabulary that looks like a misprint of a much grimmer word.'],
    [3, 'mixed',
      ['RAMPART|n|a defensive wall of earth or stone', 'FIDGET|v|to make small restless movements', 'CRASS|adj|insensitive and crude',
       '^SCULLERY|n|a small room for washing dishes|Found in older houses. Looks like an invented relation of SCULL and CUTLERY.',
       '*RAMPRANT'],
      'RAMPRANT sits beside the real RAMPANT and shares a stem with RAMPART, which makes it look like a word you have seen in print.',
      'SCULLERY is the decoy: a real domestic room whose name looks assembled from unrelated parts.'],
    [3, 'mixed',
      ['TRUANT|n|a pupil who stays away from school', 'HUMID|adj|marked by high moisture in the air', 'SPURT|n|a sudden gush or burst of effort',
       '^PLUMB|v|to measure depth; to explore thoroughly|"Plumb the depths." The silent B makes it look like a typo for PLUM.',
       '*TRUANCE'],
      'TRUANCE looks like the noun form of TRUANT — which is TRUANCY, not TRUANCE. The near miss is the trap.',
      'PLUMB is the decoy: a real verb whose silent B makes players read it as a misspelling of a fruit.'],
    [3, 'mixed',
      ['FORTITUDE|n|courage in adversity', 'CLINCH|v|to settle conclusively', 'GRAVY|n|a sauce made from meat juices',
       '^SUTLER|n|a merchant who followed an army selling provisions|Historical but genuinely recorded. Looks like a blend of SUBTLE and BUTLER.',
       '*FORTANT'],
      'FORTANT looks like a military or heraldic term, and it shares a stem with a real noun in the same round.',
      'SUTLER is the trap: a real historical trade whose name looks like a fabrication built from two familiar words.'],
    [4, 'mixed',
      ['INCULCATE|v|to instil by persistent instruction', 'WISTFUL|adj|sadly longing', 'PARIAH|n|an outcast',
       '^COMITY|n|courteous and considerate behaviour between states|"The comity of nations." One letter from COMEDY, which is the trap.',
       '*INCULCANT'],
      'INCULCANT applies -ANT to a real verb, exactly as English produced APPLICANT and DESICCANT.',
      'COMITY is the decoy: a genuine diplomatic noun that looks like a misprint of COMEDY or COMMUNITY.'],
    [4, 'mixed',
      ['SOPORIFIC|adj|tending to induce sleep', 'LULL|n|a temporary pause or interval of quiet', 'DEBACLE|n|a sudden humiliating failure',
       '^OROTUND|adj|of speech: pompous and full-sounding|Used of grandiose oratory. Looks like a misprint of ROTUND with a stray O.',
       '*SOPORANT'],
      'SOPORANT looks like a pharmaceutical term, and the -ANT ending is genuinely how many drug classes are named.',
      'OROTUND is the trap: a real adjective for pompous speech that reads as a typo for ROTUND.'],
    [5, 'mixed',
      ['SESQUIPEDALIAN|adj|given to using long words', 'ABEYANCE|n|a state of temporary suspension', 'CAVEAT|n|a warning or qualification',
       '^SATURNINE|adj|gloomy and slow to show emotion|From the planet Saturn’s supposed influence. Looks like invented astrology vocabulary.',
       '*SESQUANT'],
      'SESQUANT looks like a shortened technical form of a real Latinate word, and abbreviation of that kind does happen.',
      'SATURNINE is the decoy: a legitimate adjective of temperament that reads as fabricated planetary jargon.'],
  ],
});

export const GAMES_11_15 = [GAME_011, GAME_012, GAME_013, GAME_014, GAME_015];
