/**
 * PERKUL — daily games #001–#005 (2026-07-28 → 2026-08-01)
 *
 * Editorial rules applied to every round:
 *   · four accepted modern English words, one fabrication
 *   · three reasonably recognisable anchors, one suspicious-but-real decoy (^)
 *   · difficulty broadly climbs 1-2 → 3 → 4 → 5 across the ten rounds
 *   · at most one strongly patterned "visual family" round per game
 */
import { buildGame } from './format';

export const GAME_001 = buildGame({
  date: '2026-07-28',
  gameNumber: 1,
  label: 'Opening day',
  rounds: [
    [1, 'mixed',
      ['MEADOW|n|a field of grass and wildflowers', 'TIMBER|n|wood prepared for building', 'SPLINT|n|a rigid strip used to support a broken limb',
       '^FROND|n|the leaf of a fern or palm|A single divided leaf, chiefly of ferns and palms. Short, blunt and slightly odd-looking, which is exactly why players doubt it.',
       '*LORVEN'],
      'LORVEN uses the -EN ending of CLOVEN and RIVEN, so it reads like an old past participle rather than an invention.',
      'FROND is the trap: it is short and strange on the page, but it is an ordinary botanical noun.'],
    [2, 'mixed',
      ['GLEAM|v|to shine softly', 'HOLLOW|adj|having an empty space inside', 'SCUFF|v|to scrape or graze a surface',
       '^DEARTH|n|a scarcity or lack of something|An unfussy noun for shortage — "a dearth of evidence". The silent-looking EA and TH make it look assembled.',
       '*PRAMBLE'],
      'PRAMBLE sits between PREAMBLE and BRAMBLE, both of which give it a familiar shape and sound.',
      'DEARTH looks like a compound of DEAR and EARTH, which makes players suspect it is stitched together. It is a plain, useful word.'],
    [2, 'mixed',
      ['QUIVER|v|to tremble slightly', 'FLUTTER|v|to move with quick light irregular motion', 'MURKY|adj|dark, dim or hard to see through',
       '^SINEW|n|a tendon; toughness or strength|The fibrous cord joining muscle to bone, and by extension wiry strength. The W ending unsettles people.',
       '*SINDLE'],
      'SINDLE echoes SPINDLE, KINDLE and DWINDLE — a completely ordinary English shape.',
      'SINEW is the decoy because it sits next to the fake alphabetically and shares its opening, tempting players to pick the wrong one of the pair.'],
    [3, 'mixed',
      ['THICKET|n|a dense group of shrubs or small trees', 'WINCE|v|to flinch briefly in pain or embarrassment', 'PARRY|v|to ward off a blow',
       '^LIMPID|adj|clear and transparent; easily understood|Used of water, air or prose that is perfectly clear. It looks like a blend of LIMP and VAPID.',
       '*MORRENT'],
      'MORRENT borrows the -ENT ending of TORRENT and CURRENT and the doubled R of both, so it scans as an existing noun.',
      'LIMPID reads as a mistake for LIMPED or a cousin of LIMP, so players discard it as invented. It is a standard adjective of praise.'],
    [3, 'mixed',
      ['CANDOR|n|frankness; honest openness', 'RUMMAGE|v|to search unsystematically', 'SEVER|v|to cut off or divide',
       '^CAVIL|v|to raise trivial objections|To quibble pettily — "he cavilled at every clause". Two syllables, no obvious relatives, so it feels made up.',
       '*DELVEN'],
      'DELVEN looks like the past participle of DELVE, which is precisely the trap: English happens not to form it that way.',
      'CAVIL is legitimate but rare in speech, so it is the word most players are willing to sacrifice.'],
    [3, 'visual-family',
      ['TALLOW|n|hard animal fat used for candles and soap', 'FALLOW|adj|left unsown for a season', 'SALLOW|adj|of an unhealthy yellowish colour',
       '^MALLOW|n|a plant with pink or purple flowers|The mallow family gives us marshmallow. As a bare noun it looks like the odd one out.',
       '*NALLOW'],
      'NALLOW is built to disappear into a family of real -ALLOW words; the pattern does the lying for it.',
      'MALLOW is the decoy: unlike the other three it is a specific plant name, so it feels like the invented member.'],
    [3, 'mixed',
      ['PLUNDER|v|to rob, especially during war', 'GRIMACE|n|a twisted expression of pain or disgust', 'BROOD|v|to dwell gloomily on something',
       '^TURBID|adj|cloudy or muddy with suspended matter|Used of water and, figuratively, of confused thought. Sits uncomfortably close to TURGID.',
       '*PLENTIC'],
      'PLENTIC follows the -IC pattern of FRANTIC and PLENARY-adjacent forms, so it reads like a technical adjective.',
      'TURBID is doubted because players know TURGID and assume one of the two must be a misprint. Both are real.'],
    [4, 'mixed',
      ['SCOUR|v|to clean by hard rubbing; to search thoroughly', 'TETHER|n|a rope confining an animal', 'BLIGHT|n|a disease or ruinous influence',
       '^CHARY|adj|cautious; sparing in giving|"Chary of praise" — wary and grudging. It looks like a misspelling of CHARRY or CHERRY.',
       '*SPANDLE'],
      'SPANDLE combines SPAN with the -DLE of CANDLE and HANDLE, one of the most productive shapes in English.',
      'CHARY is the trap: unusual in speech, unmistakable in print, and easy to mistake for a typo.'],
    [4, 'mixed',
      ['FURROW|n|a long shallow trench cut by a plough', 'RANCOR|n|bitter, lasting resentment', 'QUELL|v|to suppress or subdue',
       '^ASKANCE|adv|with suspicion or disapproval|Almost always in "look askance at". The AS- opening and -ANCE ending make it look constructed.',
       '*TORVID'],
      'TORVID lands between TORPID and TURBID, two adjectives players already half-confuse, so it inherits their credibility.',
      'ASKANCE survives only inside one idiom, so players who have never read it assume it was invented for this round.'],
    [5, 'mixed',
      ['OBLIQUE|adj|slanting; indirect', 'PALLID|adj|pale, especially from illness', 'VESTIGE|n|a small remaining trace',
       '^TEMERITY|n|excessive boldness; nerve|"He had the temerity to argue." It looks like a cousin of TIMID, which is the opposite of what it means.',
       '*FRANGENT'],
      'FRANGENT uses the real Latin root behind FRANGIBLE and FRACTURE with the ordinary -ENT ending, so it looks properly derived.',
      'TEMERITY is the decoy because its sound suggests timidity while its meaning is the reverse, and that dissonance makes players distrust it.'],
  ],
});

export const GAME_002 = buildGame({
  date: '2026-07-29',
  gameNumber: 2,
  rounds: [
    [1, 'mixed',
      ['BUCKLE|v|to fasten, or to bend under strain', 'PEBBLE|n|a small smooth stone', 'SIMMER|v|to cook just below boiling',
       '^KNELL|n|the sound of a bell rung slowly for a death|"The death knell." The silent K makes it look invented to modern eyes.',
       '*CRIMBLE'],
      'CRIMBLE mixes CRUMBLE and CRIMP; the -MBLE ending is one of the most common in English.',
      'KNELL is the trap: a legitimate noun most people meet only in the phrase "death knell", and the silent K reads as fabrication.'],
    [2, 'mixed',
      ['SHUTTER|n|a hinged cover for a window', 'NUZZLE|v|to rub or push gently with the nose', 'CLAMOR|n|a loud confused noise; an insistent demand',
       '^WELT|n|a raised mark on the skin|The ridge left by a blow, also the strip in a shoe. One syllable and blunt, so it looks like a coinage.',
       '*GROVEN'],
      'GROVEN is shaped exactly like WOVEN and CLOVEN and even suggests a plural of GROVE, so it feels remembered rather than invented.',
      'WELT reads as an abbreviation of something longer, which is why it attracts suspicion; it is a plain everyday noun.'],
    [2, 'mixed',
      ['WHITTLE|v|to carve wood by cutting small slices', 'SPARSE|adj|thinly scattered', 'HAGGLE|v|to argue over a price',
       '^GLEAN|v|to gather slowly, bit by bit|Originally gathering leftover grain; now used of information. Short, and easy to mistake for CLEAN or GLEAM.',
       '*SPRELL'],
      'SPRELL uses the SPR- cluster of SPRAWL and SPRING with the -ELL of SWELL and QUELL: a legal, unremarkable English shape.',
      'GLEAN is the decoy because it sits one letter from GLEAM and CLEAN, so players assume it is a misprint of a real word.'],
    [3, 'mixed',
      ['PARCH|v|to dry out with heat', 'VIGIL|n|a period of staying awake to watch or pray', 'MEAGER|adj|lacking in quantity or quality',
       '^SLAKE|v|to quench or satisfy|"Slake a thirst", and also what you do to lime with water. It looks like a blend of SLAY and LAKE.',
       '*CANDROUS'],
      'CANDROUS carries the -OUS ending of PONDEROUS and CANDID’s stem, so it reads like an adjective someone once taught you.',
      'SLAKE is legitimate but almost entirely confined to thirst, so out of that phrase players stop trusting it.'],
    [3, 'visual-family',
      ['DOLLOP|n|a shapeless blob of something soft', 'GALLOP|v|to run at a horse’s fastest pace', 'SCALLOP|n|an edible shellfish with a fluted shell',
       '^WALLOP|v|to strike very hard|A hearty informal verb for hitting, and a noun for the blow. Beside the others it looks like the joke entry.',
       '*MALLOP'],
      'MALLOP hides inside a row of genuine -ALLOP words, where the shared pattern supplies all the plausibility it needs.',
      'WALLOP is the decoy: the most colloquial of the four, so players assume it must be the fabricated one.'],
    [3, 'mixed',
      ['DRIZZLE|n|light steady rain', 'ANVIL|n|the iron block a smith hammers on', 'PUCKER|v|to gather into small wrinkles',
       '^BRACKISH|adj|slightly salty; distasteful|Used of water where river meets sea. The BRACK- stem exists nowhere else in common English.',
       '*GRANDLE'],
      'GRANDLE joins GRAND to the -LE of DWINDLE and BRINDLE, so it reads like a dialect word with a long history.',
      'BRACKISH is doubted because its stem is unfamiliar and the -ISH ending looks like something added for the puzzle.'],
    [3, 'mixed',
      ['SHACKLE|n|a metal fastening for a prisoner’s wrist or ankle', 'BLUNDER|n|a careless mistake', 'SEETHE|v|to boil, or to be violently angry',
       '^QUAFF|v|to drink heartily|"Quaffing ale." The double F and the QU- opening make it look like invented mock-medieval English.',
       '*MOLLENT'],
      'MOLLENT uses the MOLL- of MOLLIFY with the -ENT of INDOLENT, a perfectly ordinary derivation that happens not to exist.',
      'QUAFF reads as pastiche — the sort of word a fantasy novel would coin — which is exactly why it is the trap.'],
    [4, 'mixed',
      ['SCANT|adj|barely sufficient', 'PILLAGE|v|to rob violently in wartime', 'WRENCH|v|to pull or twist suddenly',
       '^DOUR|adj|severe, stern and joyless|A dour expression, a dour landscape. Four letters, no relatives, and two accepted pronunciations.',
       '*SPARGENT'],
      'SPARGENT looks like a chemistry or botany term built on a Latin stem, and technical-sounding -ENT adjectives are usually real.',
      'DOUR is the decoy: short, unusual on the page, and frequently mistaken for a typo of SOUR or DOUBT.'],
    [4, 'mixed',
      ['TAUT|adj|stretched tight', 'HEW|v|to chop or cut with a heavy tool', 'MIRE|n|swampy ground; a difficult situation',
       '^UNCTUOUS|adj|excessively flattering; oily|Of manner: greasily ingratiating. The UNCT- cluster looks impossible in English.',
       '*TRAVENT'],
      'TRAVENT sounds like a legal or architectural term and follows the TRA- + -ENT pattern of TRANSIENT, so it passes without inspection.',
      'UNCTUOUS is the trap because it looks unpronounceable, yet it is standard vocabulary in reviews and profiles.'],
    [5, 'mixed',
      ['NADIR|n|the lowest point', 'GUILE|n|sly cunning', 'FETTER|v|to restrain or shackle',
       '^ALACRITY|n|brisk and cheerful readiness|"She agreed with alacrity." Long, Latinate and rarely spoken, so it feels manufactured.',
       '*CELERANCE'],
      'CELERANCE is built from the genuine root of CELERITY with the very common -ANCE suffix, making it the most believable word in the round.',
      'ALACRITY is the decoy precisely because the fake beside it uses a real root; the two look like siblings and only one is legitimate.'],
  ],
});

export const GAME_003 = buildGame({
  date: '2026-07-30',
  gameNumber: 3,
  rounds: [
    [1, 'mixed',
      ['LANTERN|n|a portable case holding a light', 'CRUMB|n|a small fragment of bread', 'STAGGER|v|to walk unsteadily',
       '^SPATE|n|a sudden rush or large number|"A spate of burglaries", and a river in flood. Looks like a misspelling of SPACE or SPADE.',
       '*LANTREL'],
      'LANTREL borrows the opening of LANTERN and the -REL of MONGREL and MINSTREL, so it feels like a word from the same shelf.',
      'SPATE is the trap: an ordinary journalistic noun that looks like a typing error when set beside longer words.'],
    [2, 'mixed',
      ['BRISTLE|n|a short stiff hair', 'SHUFFLE|v|to walk without lifting the feet clear of the ground', 'SMOTHER|v|to suffocate or stifle',
       '^DROSS|n|worthless material; waste|The scum on molten metal, and by extension anything worthless. The double S looks arbitrary.',
       '*GLUMBER'],
      'GLUMBER sounds like a blend of GLUM and SLUMBER, and the -MBER ending of TIMBER and LUMBER makes it read as a settled English word.',
      'DROSS is doubted because its only common use is figurative and its shape resembles a truncated word.'],
    [2, 'mixed',
      ['TRICKLE|v|to flow in a thin stream', 'GRUFF|adj|rough and abrupt in manner', 'PLUMMET|v|to fall steeply',
       '^WAN|adj|pale and weary-looking|"A wan smile." Three letters, so it looks like an abbreviation rather than an adjective.',
       '*TRUMMET'],
      'TRUMMET shares its ending with PLUMMET and its opening with TRUMPET, so the eye files it as something already known.',
      'WAN is the decoy: tiny, unusual, and easily read as an acronym or a fragment of WANT.'],
    [3, 'mixed',
      ['SQUANDER|v|to waste carelessly', 'THRESHOLD|n|a doorway; a point of beginning', 'GRAVEL|n|small loose stones',
       '^SPURIOUS|adj|false; not genuine|Of reasoning or claims: bogus. The SPUR- opening suggests horses rather than falsehood.',
       '*SPURNANT'],
      'SPURNANT joins the real verb SPURN to the -ANT of DEFIANT, and English forms adjectives that way constantly.',
      'SPURIOUS is the trap: a real and useful adjective placed beside a fabrication that shares its first five letters.'],
    [3, 'mixed',
      ['MARSHAL|v|to gather and organise', 'BRITTLE|adj|hard but easily broken', 'CINDER|n|a piece of partly burnt coal or wood',
       '^SUNDER|v|to break apart|"Sundered from his family." Survives mostly in ASUNDER, so the bare verb looks invented.',
       '*CINDRAL'],
      'CINDRAL uses the -AL ending that turns nouns into adjectives, and sits beside CINDER to borrow its authority.',
      'SUNDER is doubted because players know ASUNDER and assume the shorter form must be a back-formation invented for the puzzle.'],
    [3, 'mixed',
      ['WEDGE|n|a tapering block used to split or steady', 'FLOUNDER|v|to struggle clumsily', 'SEAR|v|to burn the surface of',
       '^CANARD|n|an unfounded rumour or story|A false report repeated as fact. It looks like a French import that never settled here — but it did.',
       '*FLOUNTER'],
      'FLOUNTER lives one letter from FLOUNDER and echoes FLAUNT, so it reads like a variant spelling rather than a fake.',
      'CANARD is the decoy: unmistakably foreign-looking, though it is standard in political writing.'],
    [3, 'visual-family',
      ['GRISTLE|n|tough cartilage in meat', 'THISTLE|n|a prickly plant with purple flowers', 'WHISTLE|v|to make a shrill sound',
       '^MISTLE|n|a large European thrush, the mistle thrush|Recorded chiefly in "mistle thrush". Beside the others it looks like the invented member.',
       '*FRISTLE'],
      'FRISTLE is camouflaged by three unarguable -ISTLE words; the family pattern is the whole deception.',
      'MISTLE is the trap: genuine but almost always attached to THRUSH, so alone it looks fabricated.'],
    [4, 'mixed',
      ['GRAPPLE|v|to struggle at close quarters', 'HAVEN|n|a place of safety', 'RIFT|n|a crack or split; a serious disagreement',
       '^RIVEN|adj|split or torn apart|The past participle of RIVE — "a country riven by war". It looks like a name or a fragment.',
       '*HAVREN'],
      'HAVREN combines HAVEN with the -REN of CHILDREN, so it reads like an old plural or place-word.',
      'RIVEN is the decoy: a real participle used constantly by journalists, yet it looks like an invented proper noun.'],
    [4, 'mixed',
      ['WITHER|v|to shrivel or fade', 'SCALD|v|to burn with hot liquid', 'GRIM|adj|forbidding; unrelentingly severe',
       '^CHURLISH|adj|rude and mean-spirited|From CHURL, a peasant. "It would be churlish to refuse." The stem is otherwise extinct.',
       '*WITHRANT'],
      'WITHRANT looks like a legal or botanical term formed from WITHER with the -ANT of RAMPANT.',
      'CHURLISH is doubted because CHURL has vanished from ordinary speech, leaving the adjective looking unsupported.'],
    [5, 'mixed',
      ['ZENITH|n|the highest point', 'PLINTH|n|the base of a column or statue', 'CLOY|v|to sicken with too much sweetness',
       '^ABASH|v|to embarrass or disconcert|Chiefly seen as UNABASHED. The bare verb looks like a misprint of ABASE or ABASH’s cousin.',
       '*PLINTIC'],
      'PLINTIC pairs PLINTH’s stem with the -IC of architectural terms, and technical adjectives are rarely questioned.',
      'ABASH is the trap: the negative UNABASHED is common, so the positive form looks invented by removing a prefix.'],
  ],
});

export const GAME_004 = buildGame({
  date: '2026-07-31',
  gameNumber: 4,
  rounds: [
    [1, 'mixed',
      ['KETTLE|n|a vessel for boiling water', 'SPROUT|v|to begin to grow', 'CLUMSY|adj|awkward in movement',
       '^SCUD|v|to move quickly, driven by the wind|Used of clouds and light boats. One syllable, so it looks like slang or an acronym.',
       '*SPROUTLE'],
      'SPROUTLE adds the frequentative -LE that gives us DAZZLE and SPARKLE, a suffix English really does use this way.',
      'SCUD is the decoy: a genuine weather verb that most readers now associate only with a missile, so it feels wrong here.'],
    [2, 'mixed',
      ['MARROW|n|the soft tissue inside bones', 'FLINCH|v|to draw back in fear or pain', 'RUGGED|adj|rough and uneven; sturdy',
       '^MOTE|n|a tiny speck, especially of dust|"A mote of dust in the sunlight." Four letters and mostly biblical, so it reads as invented.',
       '*MARROVE'],
      'MARROVE takes MARROW’s opening and the -OVE of GROVE and DROVE, giving it a settled, old-English feel.',
      'MOTE is the trap: a real noun kept alive by one famous verse, so out of that context players discard it.'],
    [2, 'mixed',
      ['SHRIVEL|v|to wrinkle and contract', 'BADGER|v|to pester persistently', 'CRISP|adj|firm and brittle; bracingly cold',
       '^EDDY|n|a circular movement of water or air|A small whirlpool. It looks exactly like a first name, which is the problem.',
       '*SHRIVANT'],
      'SHRIVANT sounds like a formal noun built from SHRIVE with -ANT, matching SERVANT and CLAIMANT.',
      'EDDY is the decoy because it is identical in form to a common nickname, so players assume it cannot also be a noun.'],
    [3, 'visual-family',
      ['FLICKER|n|a brief unsteady light', 'SNICKER|v|to laugh in a half-suppressed way', 'BICKER|v|to argue about petty things',
       '^DICKER|v|to haggle over a price or terms|Chiefly North American: to barter or negotiate pettily. It looks like the invented one.',
       '*PLICKER'],
      'PLICKER hides among four real -ICKER verbs, where the pattern alone makes it look like a word you have simply forgotten.',
      'DICKER is the trap: a legitimate verb for haggling that most players have never had cause to write down.'],
    [3, 'mixed',
      ['STIFLE|v|to smother or suppress', 'BOULDER|n|a large rounded rock', 'PRATTLE|v|to talk at length about nothing',
       '^LAUD|v|to praise highly|"Laud his achievements", and the source of LAUDABLE. Four letters, so it looks clipped.',
       '*STIFRANT'],
      'STIFRANT looks like a technical adjective; the -ANT ending on an unfamiliar stem is usually a sign of real jargon.',
      'LAUD is doubted because LAUDABLE is far commoner, so the bare verb looks like a stem someone invented backwards.'],
    [3, 'mixed',
      ['GNARLED|adj|knobbly and twisted with age', 'SPLURGE|v|to spend extravagantly', 'HAMLET|n|a very small village',
       '^GIRD|v|to encircle or prepare oneself|"Gird your loins", and the source of GIRDER and GIRDLE. Looks like a misspelling of GRID.',
       '*GNARVEL'],
      'GNARVEL keeps the improbable but real GN- opening of GNARLED and GNAW, which makes an invented word look authentic.',
      'GIRD is the decoy: an anagram of GRID and rare outside one idiom, so it reads as an error rather than a verb.'],
    [3, 'mixed',
      ['SIPHON|v|to draw off liquid through a tube', 'RUBBLE|n|broken fragments of brick and stone', 'DAPPLED|adj|marked with spots or patches',
       '^SUET|n|hard white fat used in cooking|The fat around kidneys, used in puddings and pastry. Three letters of vowel-heavy oddness.',
       '*SUETTLE'],
      'SUETTLE takes the genuine noun SUET and adds -TLE, so it looks like a diminutive that ought to exist.',
      'SUET is the trap: entirely legitimate, but so confined to old recipes that younger players read it as invented.'],
    [4, 'mixed',
      ['TRAWL|v|to fish with a dragged net; to search exhaustively', 'BEHEST|n|a command or urgent request', 'SLUICE|n|a sliding gate controlling water',
       '^DEIGN|v|to do something one considers beneath one|"She did not deign to reply." The silent G looks like a spelling mistake.',
       '*TRAWLENT'],
      'TRAWLENT joins a familiar verb to the -ENT of PREVALENT, one of the most trusted-looking endings in English.',
      'DEIGN is the decoy: its spelling is genuinely peculiar, so players who know it only by ear reject it on sight.'],
    [4, 'mixed',
      ['RANSACK|v|to search roughly and destructively', 'HOARY|adj|greyish-white with age', 'WRIT|n|a formal written court order',
       '^INURE|v|to accustom someone to something unpleasant|"Inured to hardship." The IN- prefix suggests a negative that is not there.',
       '*HOARVENT'],
      'HOARVENT looks like a meteorological term, and HOAR is a real element of HOARFROST, which lends it cover.',
      'INURE is the trap: correct, common in serious prose, and easily mistaken for a mangled form of ENSURE or INJURE.'],
    [5, 'mixed',
      ['USURP|v|to seize power wrongfully', 'PARE|v|to trim by cutting away the outside', 'TENET|n|a principle held to be true',
       '^SUCCOR|n|help given in difficulty|Assistance in time of need, also a verb. Looks like a misspelling of SUCCOUR’s cousin SUCCUMB.',
       '*USURPANCE'],
      'USURPANCE attaches the real verb USURP to -ANCE, exactly how ENDURANCE and ASSURANCE were formed. The gap in English is arbitrary.',
      'SUCCOR is the decoy: a genuine noun of relief that looks, at speed, like a typo for SUCCEED or SUCCUMB.'],
  ],
});

export const GAME_005 = buildGame({
  date: '2026-08-01',
  gameNumber: 5,
  rounds: [
    [1, 'mixed',
      ['BLOSSOM|n|a flower or mass of flowers', 'STUMBLE|v|to trip while walking', 'PANTRY|n|a small room for storing food',
       '^GRIST|n|grain to be ground; useful material|"Grist to the mill." Outside that phrase it looks like a fragment of GRISTLE.',
       '*BLOSSANT'],
      'BLOSSANT looks like a botanical adjective; pairing a known stem with -ANT is a standard English move.',
      'GRIST is the trap: a real noun preserved by a single idiom, which makes it feel like part of a longer word.'],
    [2, 'mixed',
      ['RIPPLE|n|a small wave on water', 'CROOKED|adj|bent or twisted; dishonest', 'THATCH|n|a roof covering of straw or reeds',
       '^BILGE|n|the lowest part of a ship’s hull; nonsense|Where water collects in a hull, and slang for rubbish. Looks like a blend of BULGE and BILE.',
       '*RIPPLENT'],
      'RIPPLENT reads like a physics or hydraulics term, and unfamiliar technical -ENT words are usually genuine.',
      'BILGE is the decoy because it sits between two common words and looks like a mistyping of either.'],
    [2, 'mixed',
      ['SHIVER|v|to tremble with cold', 'GRAPE|n|a small round fruit growing in bunches', 'LUMBER|v|to move heavily and clumsily',
       '^WHET|v|to sharpen, or to stimulate|"Whet a blade", "whet the appetite". Constantly confused with WET, so it looks wrong.',
       '*SHIVREL'],
      'SHIVREL uses the -REL of SQUIRREL and MONGREL on a familiar stem, which is enough to make it read as a real animal or object.',
      'WHET is the trap: correct and common in writing, yet so often mistaken for a misspelling of WET that players abandon it.'],
    [3, 'mixed',
      ['CAULDRON|n|a large metal cooking pot', 'FLEDGLING|n|a young bird; a beginner', 'TREK|v|to travel arduously on foot',
       '^SLOUGH|v|to shed skin or cast off|A snake sloughs its skin; also a muddy hollow. The -OUGH ending is genuinely bewildering.',
       '*CAULDRANT'],
      'CAULDRANT looks like an obsolete-but-documented term, and the -ANT ending gives an invented word instant respectability.',
      'SLOUGH is the decoy: real, useful, and spelled in a way that looks impossible to anyone meeting it cold.'],
    [3, 'mixed',
      ['GRUDGE|n|a persistent feeling of resentment', 'TRELLIS|n|a lattice frame supporting plants', 'HOVER|v|to remain suspended in one place',
       '^DINT|n|a dent; force or effort|"By dint of hard work." Almost extinct except in that phrase, so it reads as a typo for DENT.',
       '*TRELLANT'],
      'TRELLANT sounds like a technical noun from engineering or gardening, and it sits next to TRELLIS to borrow legitimacy.',
      'DINT is the trap: a genuine noun surviving in one idiom, and one letter from a much commoner word.'],
    [3, 'mixed',
      ['SPRAWL|v|to spread out untidily', 'MUSTY|adj|smelling stale and damp', 'GRIT|n|small hard particles; courage',
       '^BEVY|n|a group, especially of people or birds|"A bevy of reporters." It looks like a nickname or a clipped form.',
       '*SPRAWLENT'],
      'SPRAWLENT looks like planning jargon, and adding -ENT to a familiar verb is how English built PREVALENT and CORPULENT.',
      'BEVY is the decoy: a real collective noun that reads as either a name or an abbreviation.'],
    [3, 'mixed',
      ['CLENCH|v|to close tightly', 'PARAPET|n|a low protective wall along an edge', 'SMOULDER|v|to burn slowly without flame',
       '^SPLENETIC|adj|bad-tempered; irritable|From the spleen, once thought the seat of anger. Long, medical-sounding and easy to reject.',
       '*CLENCHANT'],
      'CLENCHANT resembles TRENCHANT closely enough that players may believe they have simply misremembered the spelling.',
      'SPLENETIC is the trap: a real adjective for irritability that looks like invented pseudo-medical vocabulary.'],
    [4, 'visual-family',
      ['HAMPER|v|to hinder or impede', 'TAMPER|v|to interfere with something improperly', 'PAMPER|v|to indulge with great care',
       '^SIMPER|v|to smile in a silly, affected way|A self-conscious, ingratiating smile. Beside the others it looks like the fabricated entry.',
       '*TIMPER'],
      'TIMPER is protected by four genuine -MPER verbs; the family pattern removes the instinct to examine it.',
      'SIMPER is the decoy: entirely legitimate, but the least familiar of the group and therefore the natural suspect.'],
    [4, 'mixed',
      ['SEETHING|adj|filled with intense unexpressed anger', 'PARSIMONY|n|extreme unwillingness to spend', 'BRACE|v|to prepare for something difficult',
       '^FEIGN|v|to pretend or simulate|"Feign surprise." The EI spelling and silent G make it look like a foreign import.',
       '*PARSIMENT'],
      'PARSIMENT looks like a legal or accounting term formed from the same root as PARSIMONY with the -MENT of JUDGMENT.',
      'FEIGN is the trap: standard English whose spelling looks so improbable that players hunting an invented word land on it.'],
    [5, 'mixed',
      ['SANGUINE|adj|optimistic, especially in a difficult situation', 'QUOTIDIAN|adj|daily; ordinary', 'ARDOR|n|great enthusiasm or passion',
       '^FULSOME|adj|excessively flattering; cloying|"Fulsome praise" — properly a criticism, not a compliment. The FUL- looks like a misuse of FULL.',
       '*SANGUENT'],
      'SANGUENT uses the true Latin root of SANGUINE with the -ENT of PUNGENT, so it looks like a legitimate sibling.',
      'FULSOME is the decoy: real, frequently misused, and structurally odd enough that players suspect it was assembled for the puzzle.'],
  ],
});

export const GAMES_01_05 = [GAME_001, GAME_002, GAME_003, GAME_004, GAME_005];
